window.GACHI_ENTRIES = [
  {
    id: "the",
    rank: 1,
    type: "word",
    term: "the",
    ipa: "/ðə, ði/",
    pos: "article",
    meanings: ["その", "例の", "共通認識のもの"],
    core: "話し手と聞き手が同じものを指せるように、名詞へ小さなスポットライトを当てる。",
    usage: ["すでに出たもの、場にあるもの、唯一だとわかるものに付く。", "母音の前や強調では /ði/ になりやすい。"],
    examples: [
      ["Can you close the door?", "そのドアを閉めてくれる？"],
      ["The thing is, I forgot my phone.", "問題は、携帯を忘れたってことなんだ。"],
    ],
    chunks: ["the thing is", "the same", "the other day"],
  },
  {
    id: "i",
    rank: 2,
    type: "word",
    term: "I",
    ipa: "/aɪ/",
    pos: "pronoun",
    meanings: ["私は", "自分は"],
    core: "話し手である自分を、会話の出発点として置く。",
    usage: ["意見、気持ち、経験を出すときの基本の主語。", "会話では I think, I mean, I guess が非常に多い。"],
    examples: [
      ["I think we should wait.", "待ったほうがいいと思う。"],
      ["I didn't know that.", "それは知らなかった。"],
    ],
    chunks: ["I think", "I mean", "I guess", "I don't know"],
  },
  {
    id: "you",
    rank: 3,
    type: "word",
    term: "you",
    ipa: "/juː, jə/",
    pos: "pronoun",
    meanings: ["あなた", "みんな", "一般に人は"],
    core: "目の前の相手、または人一般へ視点を向ける。",
    usage: ["相手を直接指すほか、一般論の you もよく使う。", "弱く読むと /jə/ に近くなる。"],
    examples: [
      ["Do you want some coffee?", "コーヒーいる？"],
      ["You never know.", "何が起きるかわからないよ。"],
    ],
    chunks: ["you know", "you mean", "do you want", "thank you"],
  },
  {
    id: "be",
    rank: 4,
    type: "word",
    term: "be",
    ipa: "/biː/",
    pos: "verb",
    meanings: ["ある", "いる", "〜である"],
    core: "人や物を、ある状態・場所・役割にそっと置く。",
    usage: ["am, are, is, was, were などに形を変える。", "存在、状態、進行形、受け身の土台になる。"],
    examples: [
      ["I'll be there in ten minutes.", "10分でそこに着くよ。"],
      ["It's going to be fine.", "きっとうまくいくよ。"],
    ],
    chunks: ["be right back", "be careful", "be into"],
  },
  {
    id: "to",
    rank: 5,
    type: "word",
    term: "to",
    ipa: "/tuː, tə/",
    pos: "preposition",
    meanings: ["〜へ", "〜に", "〜するために"],
    core: "ある地点・相手・目的へ向かう矢印。",
    usage: ["方向、到達点、受け手、目的を表す。", "不定詞では動作へ向かう感じを作る。"],
    examples: [
      ["I'm going to the store.", "店に行くところ。"],
      ["I need to talk to you.", "君に話す必要がある。"],
    ],
    chunks: ["have to", "want to", "talk to", "go to"],
  },
  {
    id: "and",
    rank: 6,
    type: "word",
    term: "and",
    ipa: "/ænd, ən/",
    pos: "conjunction",
    meanings: ["そして", "〜と", "それに"],
    core: "要素を横につなげて、流れを続ける接着剤。",
    usage: ["単語、文、出来事を自然につなげる。", "会話では弱く /ən/ のように聞こえやすい。"],
    examples: [
      ["Come in and sit down.", "入って座って。"],
      ["I called and left a message.", "電話してメッセージを残した。"],
    ],
    chunks: ["and then", "and so", "you and me"],
  },
  {
    id: "a",
    rank: 7,
    type: "word",
    term: "a / an",
    ipa: "/ə, ən/",
    pos: "article",
    meanings: ["ひとつの", "ある", "種類としての"],
    core: "輪郭のある一つを、たくさんある中から軽く取り出す。",
    usage: ["初めて出す名詞や、職業・種類を言うときに使う。", "母音の音の前では an。つづりではなく音で決まる。"],
    examples: [
      ["I need a minute.", "少し時間が必要。"],
      ["She's an engineer.", "彼女はエンジニアです。"],
    ],
    chunks: ["a little", "a lot", "a couple of"],
  },
  {
    id: "it",
    rank: 8,
    type: "word",
    term: "it",
    ipa: "/ɪt/",
    pos: "pronoun",
    meanings: ["それ", "状況", "時間・天気の主語"],
    core: "話題になっている物事や状況を、小さく受け止める代名詞。",
    usage: ["物、状況、前の文全体を受ける。", "It's ... で天気・時間・感想をすばやく言える。"],
    examples: [
      ["It sounds good.", "よさそうだね。"],
      ["I can do it.", "それできるよ。"],
    ],
    chunks: ["it's okay", "that's it", "make it", "it depends"],
  },
  {
    id: "that",
    rank: 9,
    type: "word",
    term: "that",
    ipa: "/ðæt/",
    pos: "determiner",
    meanings: ["あれ", "それ", "〜ということ"],
    core: "少し離れたものや、まとめた内容を指差す。",
    usage: ["名詞の前では「あの」、単独では「それ」。", "文を受けて「それは」と言うときに強い。"],
    examples: [
      ["That's exactly what I mean.", "まさにそれが言いたいこと。"],
      ["I didn't know that you were here.", "君がここにいるとは知らなかった。"],
    ],
    chunks: ["that's why", "like that", "that makes sense"],
  },
  {
    id: "of",
    rank: 10,
    type: "word",
    term: "of",
    ipa: "/əv, ʌv/",
    pos: "preposition",
    meanings: ["〜の", "〜から成る", "〜について"],
    core: "全体と部分、持ち主と中身をゆるく結びつける。",
    usage: ["日本語の「の」に近いが、材料・所属・内容にも広い。", "a lot of, kind of など会話の塊で覚えると強い。"],
    examples: [
      ["A friend of mine lives here.", "私の友人がここに住んでいる。"],
      ["I'm kind of tired.", "ちょっと疲れてる。"],
    ],
    chunks: ["a lot of", "kind of", "out of", "because of"],
  },
  {
    id: "in",
    rank: 11,
    type: "word",
    term: "in",
    ipa: "/ɪn/",
    pos: "preposition",
    meanings: ["〜の中に", "〜で", "〜後に"],
    core: "空間・時間・状況の中に入っている感覚。",
    usage: ["場所、期間、状態、分野の内側を表す。", "in a minute のように未来の時間にも使う。"],
    examples: [
      ["I'll be there in five minutes.", "5分後に行くよ。"],
      ["She's in a meeting.", "彼女は会議中です。"],
    ],
    chunks: ["in case", "in front of", "in the middle of"],
  },
  {
    id: "is",
    rank: 12,
    type: "word",
    term: "is",
    ipa: "/ɪz, z/",
    pos: "verb",
    meanings: ["〜です", "〜にいる", "〜である"],
    core: "一つの主語を、今の状態や場所に結びつける。",
    usage: ["he, she, it, 単数名詞の現在に使う。", "会話では it's, that's, he's の形で頻出。"],
    examples: [
      ["It's not a big deal.", "大したことじゃないよ。"],
      ["Where is everyone?", "みんなどこ？"],
    ],
    chunks: ["it is", "that is", "where is", "is there"],
  },
  {
    id: "for",
    rank: 13,
    type: "word",
    term: "for",
    ipa: "/fɔːr, fər/",
    pos: "preposition",
    meanings: ["〜のために", "〜に向けて", "〜の間"],
    core: "利益・目的・期間へ向かって差し出す感じ。",
    usage: ["相手の利益、目的、理由、期間を表す。", "Thanks for ... で感謝の理由を置く。"],
    examples: [
      ["This is for you.", "これは君に。"],
      ["Thanks for helping me.", "手伝ってくれてありがとう。"],
    ],
    chunks: ["for now", "for sure", "look for", "wait for"],
  },
  {
    id: "we",
    rank: 14,
    type: "word",
    term: "we",
    ipa: "/wiː/",
    pos: "pronoun",
    meanings: ["私たちは", "こちらは"],
    core: "話し手を含むグループを一つにまとめる。",
    usage: ["相手を含む場合と含まない場合がある。", "提案では Should we ...? が自然。"],
    examples: [
      ["We should talk later.", "あとで話したほうがいいね。"],
      ["Are we good?", "これで大丈夫？"],
    ],
    chunks: ["we need to", "should we", "are we good"],
  },
  {
    id: "on",
    rank: 15,
    type: "word",
    term: "on",
    ipa: "/ɑːn/",
    pos: "preposition",
    meanings: ["〜の上に", "〜中で", "〜に接して"],
    core: "表面や流れに接触している感じ。",
    usage: ["場所、曜日、機器の稼働、話題への接触を表す。", "on time は決まった時刻に接しているイメージ。"],
    examples: [
      ["I'm on my way.", "今向かってる。"],
      ["Let's talk on Monday.", "月曜に話そう。"],
    ],
    chunks: ["on time", "on my way", "on the phone"],
  },
  {
    id: "do",
    rank: 16,
    type: "word",
    term: "do",
    ipa: "/duː, də/",
    pos: "verb",
    meanings: ["する", "行う", "疑問・否定を作る"],
    core: "何かを実行する、または文を動かすためのエンジン。",
    usage: ["一般動詞の疑問文・否定文を作る。", "Do you ...? は会話の入口として非常に多い。"],
    examples: [
      ["What do you do?", "仕事は何をしているの？"],
      ["I don't think so.", "そうは思わない。"],
    ],
    chunks: ["do you", "don't", "do that", "what do you mean"],
  },
  {
    id: "have",
    rank: 17,
    type: "word",
    term: "have",
    ipa: "/hæv, həv/",
    pos: "verb",
    meanings: ["持っている", "食べる", "経験する"],
    core: "自分の領域の中に、物・時間・経験を持つ。",
    usage: ["所有だけでなく、予定・経験・食事にも使う。", "have to は外から来る必要性を持っている感じ。"],
    examples: [
      ["I have a question.", "質問があります。"],
      ["We have to leave now.", "もう出ないといけない。"],
    ],
    chunks: ["have to", "have a good one", "have no idea"],
  },
  {
    id: "not",
    rank: 18,
    type: "word",
    term: "not",
    ipa: "/nɑːt/",
    pos: "adverb",
    meanings: ["〜でない", "〜しない"],
    core: "文の内容にストップをかけて、否定へ反転させる。",
    usage: ["be動詞・助動詞の後ろに置く。", "not really は柔らかい否定としてよく使う。"],
    examples: [
      ["I'm not sure.", "よくわからない。"],
      ["Not really.", "そうでもないかな。"],
    ],
    chunks: ["not sure", "not really", "not at all"],
  },
  {
    id: "this",
    rank: 19,
    type: "word",
    term: "this",
    ipa: "/ðɪs/",
    pos: "determiner",
    meanings: ["これ", "この", "今の"],
    core: "手元・目の前・今ここにあるものを指差す。",
    usage: ["近い物、今の状況、これから言う内容を示す。", "This is ... は紹介や説明の基本形。"],
    examples: [
      ["This is really good.", "これ本当においしい。"],
      ["I can't do this right now.", "今これはできない。"],
    ],
    chunks: ["this one", "this time", "this is it"],
  },
  {
    id: "but",
    rank: 20,
    type: "word",
    term: "but",
    ipa: "/bʌt, bət/",
    pos: "conjunction",
    meanings: ["でも", "しかし", "ただ"],
    core: "前の流れに小さなブレーキをかけて、別方向へ曲げる。",
    usage: ["反対、例外、遠慮した言い足しに使う。", "会話では文頭の But ... も自然。"],
    examples: [
      ["I like it, but it's expensive.", "好きだけど高いね。"],
      ["Sorry, but I have to go.", "ごめん、でも行かないと。"],
    ],
    chunks: ["but still", "but then", "sorry but"],
  },
  {
    id: "what",
    rank: 21,
    type: "word",
    term: "what",
    ipa: "/wʌt, wət/",
    pos: "pronoun",
    meanings: ["何", "どんなもの", "〜すること"],
    core: "わからない中身を空欄として差し出す。",
    usage: ["情報をたずねる基本語。", "What about ...? で話題を向ける。"],
    examples: [
      ["What are you doing?", "何してるの？"],
      ["What about tomorrow?", "明日はどう？"],
    ],
    chunks: ["what if", "what about", "what do you mean"],
  },
  {
    id: "so",
    rank: 22,
    type: "word",
    term: "so",
    ipa: "/soʊ/",
    pos: "adverb",
    meanings: ["だから", "とても", "そう"],
    core: "前の内容を受けて、結果や程度を押し出す。",
    usage: ["理由から結果へ進める。", "so good のように程度を強める。"],
    examples: [
      ["I was tired, so I went home.", "疲れていたので帰った。"],
      ["That's so nice of you.", "それは本当に親切だね。"],
    ],
    chunks: ["so far", "so much", "so that", "and so"],
  },
  {
    id: "get",
    rank: 23,
    type: "word",
    term: "get",
    ipa: "/ɡet/",
    pos: "verb",
    meanings: ["得る", "着く", "わかる", "〜になる"],
    core: "動いて、何かを自分の側に取り込む。",
    usage: ["物を手に入れる、場所に着く、状態になる、理解する。", "会話では get it, get to, get ready が多い。"],
    examples: [
      ["I get it now.", "今わかった。"],
      ["Let's get some lunch.", "昼ごはんを食べよう。"],
    ],
    chunks: ["get it", "get to", "get ready", "get along"],
  },
  {
    id: "can",
    rank: 24,
    type: "word",
    term: "can",
    ipa: "/kæn, kən/",
    pos: "modal verb",
    meanings: ["できる", "してもよい", "あり得る"],
    core: "可能性や許可のドアが開いている。",
    usage: ["能力、依頼、許可、可能性を表す。", "Can you ...? は依頼の定番。"],
    examples: [
      ["Can you help me?", "手伝ってくれる？"],
      ["It can happen to anyone.", "誰にでも起こり得るよ。"],
    ],
    chunks: ["can I", "can you", "I can't", "can't wait"],
  },
  {
    id: "just",
    rank: 25,
    type: "word",
    term: "just",
    ipa: "/dʒʌst/",
    pos: "adverb",
    meanings: ["ただ", "ちょうど", "ほんの", "今さっき"],
    core: "範囲を細く絞って、余計なものを外す。",
    usage: ["軽くする、限定する、時間の近さを出す。", "Just a second. は会話で非常に便利。"],
    examples: [
      ["Just give me a second.", "ちょっとだけ待って。"],
      ["I just got here.", "今着いたばかり。"],
    ],
    chunks: ["just a sec", "just in case", "just like"],
  },
  {
    id: "like",
    rank: 26,
    type: "word",
    term: "like",
    ipa: "/laɪk/",
    pos: "verb/preposition",
    meanings: ["好き", "〜のような", "例えば"],
    core: "心が近づく、または形や感じが近いものへ寄せる。",
    usage: ["好み、類似、例示、口語のつなぎに使う。", "Would you like ...? は丁寧な申し出。"],
    examples: [
      ["I like the way you said that.", "その言い方いいね。"],
      ["It's like five minutes away.", "5分くらいの距離だよ。"],
    ],
    chunks: ["feel like", "look like", "would like", "like this"],
  },
  {
    id: "know",
    rank: 27,
    type: "word",
    term: "know",
    ipa: "/noʊ/",
    pos: "verb",
    meanings: ["知っている", "わかっている"],
    core: "情報や人が、自分の中でつながっている状態。",
    usage: ["知識、認識、人との面識に使う。", "I don't know は会話の超頻出形。"],
    examples: [
      ["Do you know where she is?", "彼女がどこにいるか知ってる？"],
      ["I know what you mean.", "言いたいことはわかるよ。"],
    ],
    chunks: ["you know", "I know", "don't know", "let me know"],
  },
  {
    id: "go",
    rank: 28,
    type: "word",
    term: "go",
    ipa: "/ɡoʊ/",
    pos: "verb",
    meanings: ["行く", "進む", "うまくいく"],
    core: "今いる場所や状態から、別の方向へ進む。",
    usage: ["移動、進行、予定、状態の変化に使う。", "How's it going? は挨拶でよく使う。"],
    examples: [
      ["I have to go.", "行かなきゃ。"],
      ["How did it go?", "どうだった？"],
    ],
    chunks: ["go ahead", "go for it", "go with", "going to"],
  },
  {
    id: "was",
    rank: 29,
    type: "word",
    term: "was",
    ipa: "/wʌz, wəz/",
    pos: "verb",
    meanings: ["〜だった", "〜にいた"],
    core: "過去の一点で、主語を状態や場所に置く。",
    usage: ["I, he, she, it, 単数名詞の過去に使う。", "会話では I was like ... で当時の反応を言える。"],
    examples: [
      ["I was busy yesterday.", "昨日は忙しかった。"],
      ["That was really helpful.", "それは本当に助かった。"],
    ],
    chunks: ["I was like", "that was", "was going to"],
  },
  {
    id: "my",
    rank: 30,
    type: "word",
    term: "my",
    ipa: "/maɪ/",
    pos: "determiner",
    meanings: ["私の"],
    core: "物や人を、自分の領域にあるものとして示す。",
    usage: ["所有だけでなく、関係・担当・経験にも使う。", "my bad はカジュアルな謝罪。"],
    examples: [
      ["My phone is dead.", "携帯の充電が切れた。"],
      ["My bad. I forgot.", "ごめん、忘れてた。"],
    ],
    chunks: ["my bad", "my turn", "my point is"],
  },
  {
    id: "will",
    rank: 31,
    type: "word",
    term: "will",
    ipa: "/wɪl, əl/",
    pos: "modal verb",
    meanings: ["〜するつもり", "〜だろう"],
    core: "これから先へ向かう意志や見込みを置く。",
    usage: ["その場で決める未来、予測、約束に使う。", "I'll ... は会話で最も軽い約束形の一つ。"],
    examples: [
      ["I will call you later.", "あとで電話するね。"],
      ["It'll be okay.", "大丈夫だよ。"],
    ],
    chunks: ["I'll", "we'll", "will be", "will do"],
  },
  {
    id: "all",
    rank: 32,
    type: "word",
    term: "all",
    ipa: "/ɔːl/",
    pos: "determiner",
    meanings: ["すべて", "全員", "まったく"],
    core: "残りなく全体を包み込む。",
    usage: ["全体、全員、強調に使う。", "all right は了承・状態・間投詞として頻出。"],
    examples: [
      ["That's all I need.", "必要なのはそれだけ。"],
      ["Are you all right?", "大丈夫？"],
    ],
    chunks: ["all right", "all the time", "after all", "that's all"],
  },
  {
    id: "there",
    rank: 33,
    type: "word",
    term: "there",
    ipa: "/ðer/",
    pos: "adverb",
    meanings: ["そこに", "存在を示す"],
    core: "自分から少し離れた場所、または存在の場を指す。",
    usage: ["場所を示すほか、There is/are で存在を出す。", "there you go は渡す・完了・理解の合図。"],
    examples: [
      ["There's one more thing.", "もう一つある。"],
      ["I'll meet you there.", "そこで会おう。"],
    ],
    chunks: ["there is", "there are", "there you go", "over there"],
  },
  {
    id: "one",
    rank: 34,
    type: "word",
    term: "one",
    ipa: "/wʌn/",
    pos: "number/pronoun",
    meanings: ["一つ", "もの", "人"],
    core: "まとまりを一つとして数えたり、前の名詞を受けたりする。",
    usage: ["数字だけでなく、one more, this one のように代名詞で使う。", "someone, anyone などの核にもなる。"],
    examples: [
      ["Can I have one?", "一つもらっていい？"],
      ["This one is better.", "こっちのほうがいい。"],
    ],
    chunks: ["one more", "this one", "no one", "the one"],
  },
  {
    id: "about",
    rank: 35,
    type: "word",
    term: "about",
    ipa: "/əˈbaʊt/",
    pos: "preposition/adverb",
    meanings: ["〜について", "だいたい", "〜の周りに"],
    core: "話題や数値の周辺をぐるっと囲む。",
    usage: ["話題、概算、周辺性を表す。", "How about ...? で提案や確認に使う。"],
    examples: [
      ["What are you talking about?", "何の話をしてるの？"],
      ["How about Friday?", "金曜はどう？"],
    ],
    chunks: ["how about", "what about", "about to", "talk about"],
  },
  {
    id: "out",
    rank: 36,
    type: "word",
    term: "out",
    ipa: "/aʊt/",
    pos: "adverb",
    meanings: ["外へ", "切れて", "終わって"],
    core: "内側から外側へ出る、または範囲から外れる。",
    usage: ["場所の外、在庫切れ、完了、公開に使う。", "find out は外へ取り出して知るイメージ。"],
    examples: [
      ["Let's go out tonight.", "今夜出かけよう。"],
      ["I found out yesterday.", "昨日わかった。"],
    ],
    chunks: ["out of", "find out", "check out", "work out"],
  },
  {
    id: "if",
    rank: 37,
    type: "word",
    term: "if",
    ipa: "/ɪf/",
    pos: "conjunction",
    meanings: ["もし", "〜かどうか"],
    core: "まだ確定していない条件の扉を開く。",
    usage: ["条件、仮定、確認の間接疑問に使う。", "What if ...? で可能性を投げる。"],
    examples: [
      ["If you're free, call me.", "空いてたら電話して。"],
      ["I don't know if I can go.", "行けるかどうかわからない。"],
    ],
    chunks: ["what if", "if you want", "if so", "even if"],
  },
  {
    id: "me",
    rank: 38,
    type: "word",
    term: "me",
    ipa: "/miː/",
    pos: "pronoun",
    meanings: ["私を", "私に"],
    core: "動作や影響を受ける自分。",
    usage: ["目的語として使う。", "Let me ... は自分が何かする許可や提案。"],
    examples: [
      ["Let me check.", "確認するね。"],
      ["Can you send it to me?", "それを送ってくれる？"],
    ],
    chunks: ["let me", "tell me", "with me", "for me"],
  },
  {
    id: "your",
    rank: 39,
    type: "word",
    term: "your",
    ipa: "/jʊr, jər/",
    pos: "determiner",
    meanings: ["あなたの", "あなたたちの"],
    core: "相手の領域に属するものとして示す。",
    usage: ["所有、関係、担当、意見に使う。", "What's your ...? は会話開始に強い。"],
    examples: [
      ["What's your name?", "名前は何ですか？"],
      ["I like your idea.", "君のアイデアいいね。"],
    ],
    chunks: ["your turn", "your call", "your place"],
  },
  {
    id: "going-to",
    rank: 40,
    type: "phrase",
    term: "going to",
    ipa: "/ˈɡoʊɪŋ tə, ˈɡənə/",
    pos: "phrase",
    meanings: ["〜する予定", "〜になりそう"],
    core: "すでにそちらへ向かって動き出している未来。",
    usage: ["予定や根拠のある未来を表す。", "会話では gonna /ˈɡənə/ と縮みやすい。"],
    examples: [
      ["I'm going to call her.", "彼女に電話するつもり。"],
      ["It's going to rain.", "雨が降りそう。"],
    ],
    chunks: ["I'm gonna", "are you gonna", "going to be"],
  },
  {
    id: "they",
    rank: 41,
    type: "word",
    term: "they",
    ipa: "/ðeɪ/",
    pos: "pronoun",
    meanings: ["彼らは", "それらは", "その人は"],
    core: "自分と相手から離れた複数、または性別を特定しない人を指す。",
    usage: ["人・物の複数を受ける。", "単数の they は性別不明・不特定の人にも使われる。"],
    examples: [
      ["They said it was okay.", "大丈夫だと言っていたよ。"],
      ["Someone left their bag here.", "誰かがバッグをここに置いていった。"],
    ],
    chunks: ["they say", "they are", "they have"],
  },
  {
    id: "say",
    rank: 42,
    type: "word",
    term: "say",
    ipa: "/seɪ/",
    pos: "verb",
    meanings: ["言う", "書いてある", "仮に〜とする"],
    core: "言葉や情報を外へ出す。",
    usage: ["発言、表示、提案、仮定に使う。", "What did you say? は聞き返しの基本。"],
    examples: [
      ["What did she say?", "彼女は何て言った？"],
      ["Let's say we leave at six.", "6時に出るとしよう。"],
    ],
    chunks: ["say that", "let's say", "I would say"],
  },
  {
    id: "would",
    rank: 43,
    type: "word",
    term: "would",
    ipa: "/wʊd, əd/",
    pos: "modal verb",
    meanings: ["〜だろう", "〜してくれる", "〜したものだった"],
    core: "現実から少し距離を置いて、やわらかく可能性を出す。",
    usage: ["丁寧な依頼、仮定、過去の習慣に使う。", "I'd like ... は丁寧な希望。"],
    examples: [
      ["Would you mind opening the window?", "窓を開けてもらえますか？"],
      ["I would do the same thing.", "私も同じことをすると思う。"],
    ],
    chunks: ["would like", "would you", "I would", "that would be"],
  },
  {
    id: "as",
    rank: 44,
    type: "word",
    term: "as",
    ipa: "/æz, əz/",
    pos: "conjunction/preposition",
    meanings: ["〜として", "〜のように", "〜するとき"],
    core: "二つのものを同じ線上に並べる。",
    usage: ["役割、同時性、比較、理由に使う。", "as soon as で「〜したらすぐ」。"],
    examples: [
      ["Use this as a guide.", "これをガイドとして使って。"],
      ["As soon as I get home, I'll call you.", "家に着いたらすぐ電話する。"],
    ],
    chunks: ["as soon as", "as well", "as long as", "as if"],
  },
  {
    id: "at",
    rank: 45,
    type: "word",
    term: "at",
    ipa: "/æt, ət/",
    pos: "preposition",
    meanings: ["〜で", "〜に", "〜をめがけて"],
    core: "一点にピンを刺す。",
    usage: ["時刻、地点、対象への狙いを表す。", "at least, at all など塊で多い。"],
    examples: [
      ["Let's meet at seven.", "7時に会おう。"],
      ["I'm good at cooking.", "料理が得意です。"],
    ],
    chunks: ["at least", "at all", "at home", "look at"],
  },
  {
    id: "or",
    rank: 46,
    type: "word",
    term: "or",
    ipa: "/ɔːr, ər/",
    pos: "conjunction",
    meanings: ["または", "それとも", "つまり"],
    core: "選択肢を横に並べて、どちらかへ分ける。",
    usage: ["選択、言い換え、否定文の列挙に使う。", "or something はぼかしとして頻出。"],
    examples: [
      ["Do you want coffee or tea?", "コーヒーか紅茶いる？"],
      ["Call me or send a text.", "電話かメッセージして。"],
    ],
    chunks: ["or not", "or something", "sooner or later"],
  },
  {
    id: "are",
    rank: 47,
    type: "word",
    term: "are",
    ipa: "/ɑːr, ər/",
    pos: "verb",
    meanings: ["〜です", "〜にいる"],
    core: "複数や you を、今の状態・場所に置く。",
    usage: ["you, we, they, 複数名詞の現在に使う。", "How are you? の核。"],
    examples: [
      ["Are you ready?", "準備できた？"],
      ["We are almost there.", "もうすぐ着くよ。"],
    ],
    chunks: ["are you", "we are", "they are", "how are"],
  },
  {
    id: "from",
    rank: 48,
    type: "word",
    term: "from",
    ipa: "/frʌm, frəm/",
    pos: "preposition",
    meanings: ["〜から", "〜出身", "〜によって"],
    core: "出発点や源を示す。",
    usage: ["場所、時点、原因、材料、出身に使う。", "hear from は相手から連絡が来る感じ。"],
    examples: [
      ["Where are you from?", "出身はどこ？"],
      ["I heard from him yesterday.", "昨日彼から連絡があった。"],
    ],
    chunks: ["from now on", "from time to time", "hear from"],
  },
  {
    id: "with",
    rank: 49,
    type: "word",
    term: "with",
    ipa: "/wɪð, wɪθ/",
    pos: "preposition",
    meanings: ["〜と一緒に", "〜を持って", "〜で"],
    core: "何かがそばに付いている状態。",
    usage: ["同伴、道具、付属、関係を表す。", "deal with は相手に向き合って処理する感じ。"],
    examples: [
      ["I'm with a friend.", "友だちと一緒にいる。"],
      ["Can you help me with this?", "これ手伝ってくれる？"],
    ],
    chunks: ["with me", "with you", "deal with", "go with"],
  },
  {
    id: "he",
    rank: 50,
    type: "word",
    term: "he",
    ipa: "/hiː, i/",
    pos: "pronoun",
    meanings: ["彼は"],
    core: "話題の男性を主語として立てる。",
    usage: ["男性や男性として示される人を受ける。", "弱く読むと h が落ちて /i/ のように聞こえることがある。"],
    examples: [
      ["He said he was sorry.", "彼は謝っていたよ。"],
      ["Do you know where he is?", "彼がどこにいるか知ってる？"],
    ],
    chunks: ["he is", "he was", "he said"],
  },
  {
    id: "she",
    rank: 51,
    type: "word",
    term: "she",
    ipa: "/ʃiː/",
    pos: "pronoun",
    meanings: ["彼女は"],
    core: "話題の女性を主語として立てる。",
    usage: ["女性や女性として示される人を受ける。", "she's は she is / she has の両方になり得る。"],
    examples: [
      ["She's on her way.", "彼女は向かっているところ。"],
      ["She told me to wait.", "彼女は待つように言った。"],
    ],
    chunks: ["she is", "she was", "she said"],
  },
  {
    id: "make",
    rank: 52,
    type: "word",
    term: "make",
    ipa: "/meɪk/",
    pos: "verb",
    meanings: ["作る", "〜させる", "間に合う"],
    core: "材料や状況に働きかけて、新しい状態を作る。",
    usage: ["作成、原因、決定、到達に使う。", "make sense は意味が形になる感じ。"],
    examples: [
      ["That makes sense.", "それは納得できる。"],
      ["Can you make it tonight?", "今夜来られる？"],
    ],
    chunks: ["make sure", "make sense", "make it", "make up"],
  },
  {
    id: "look",
    rank: 53,
    type: "word",
    term: "look",
    ipa: "/lʊk/",
    pos: "verb",
    meanings: ["見る", "〜に見える", "探す"],
    core: "目や注意を向ける。",
    usage: ["見る動作、外見の判断、注意喚起に使う。", "Look, ... は話を切り出す合図。"],
    examples: [
      ["You look tired.", "疲れて見えるよ。"],
      ["I'm looking for my keys.", "鍵を探している。"],
    ],
    chunks: ["look at", "look for", "look like", "look up"],
  },
  {
    id: "think",
    rank: 54,
    type: "word",
    term: "think",
    ipa: "/θɪŋk/",
    pos: "verb",
    meanings: ["思う", "考える"],
    core: "頭の中で考えを動かし、意見として置く。",
    usage: ["意見、予想、判断を柔らかく出す。", "I think は断定を少しやわらげる。"],
    examples: [
      ["I think it's a good idea.", "いい考えだと思う。"],
      ["What do you think?", "どう思う？"],
    ],
    chunks: ["I think", "think about", "think of", "I don't think"],
  },
  {
    id: "take",
    rank: 55,
    type: "word",
    term: "take",
    ipa: "/teɪk/",
    pos: "verb",
    meanings: ["取る", "連れて行く", "時間がかかる", "受け入れる"],
    core: "何かを自分の側に取って、次の場所や状態へ運ぶ。",
    usage: ["物を取る、移動、時間、薬、選択に広く使う。", "take care は世話として受け持つ感じ。"],
    examples: [
      ["Take your time.", "ゆっくりでいいよ。"],
      ["It takes about ten minutes.", "10分くらいかかる。"],
    ],
    chunks: ["take care", "take a look", "take it easy", "take off"],
  },
  {
    id: "want",
    rank: 56,
    type: "word",
    term: "want",
    ipa: "/wɑːnt/",
    pos: "verb",
    meanings: ["欲しい", "〜したい"],
    core: "足りないものや向かいたい行動へ心が伸びる。",
    usage: ["欲求、希望、依頼に使う。", "wanna /ˈwɑːnə/ は want to の会話形。"],
    examples: [
      ["I want to try again.", "もう一度やってみたい。"],
      ["Do you want me to call?", "私が電話しようか？"],
    ],
    chunks: ["want to", "wanna", "do you want", "want me to"],
  },
  {
    id: "see",
    rank: 57,
    type: "word",
    term: "see",
    ipa: "/siː/",
    pos: "verb",
    meanings: ["見る", "会う", "わかる"],
    core: "目や理解で、対象をはっきり捉える。",
    usage: ["視覚、面会、理解、確認に使う。", "I see は理解した合図。"],
    examples: [
      ["I see what you mean.", "言いたいことはわかる。"],
      ["See you tomorrow.", "また明日。"],
    ],
    chunks: ["I see", "see you", "let's see", "see if"],
  },
  {
    id: "come",
    rank: 58,
    type: "word",
    term: "come",
    ipa: "/kʌm/",
    pos: "verb",
    meanings: ["来る", "起こる", "思い浮かぶ"],
    core: "話し手や基準点のほうへ近づく。",
    usage: ["移動、順番、出来事の到来に使う。", "come on は促し・驚き・不満まで広い。"],
    examples: [
      ["Can you come here?", "こっちに来てくれる？"],
      ["Come on, let's go.", "ほら、行こう。"],
    ],
    chunks: ["come on", "come back", "come with", "come up"],
  },
  {
    id: "time",
    rank: 59,
    type: "word",
    term: "time",
    ipa: "/taɪm/",
    pos: "noun",
    meanings: ["時間", "回", "時期"],
    core: "出来事が置かれる流れや一点。",
    usage: ["時刻、期間、回数、機会に使う。", "at the same time は同時に、または一方で。"],
    examples: [
      ["What time is it?", "今何時？"],
      ["I don't have time right now.", "今は時間がない。"],
    ],
    chunks: ["on time", "this time", "next time", "all the time"],
  },
  {
    id: "really",
    rank: 60,
    type: "word",
    term: "really",
    ipa: "/ˈriːəli/",
    pos: "adverb",
    meanings: ["本当に", "とても", "まさか"],
    core: "現実味や強さをぐっと濃くする。",
    usage: ["強調、確認、驚きに使う。", "Not really はやわらかい否定。"],
    examples: [
      ["I really appreciate it.", "本当に感謝しています。"],
      ["Really? I didn't know.", "本当？知らなかった。"],
    ],
    chunks: ["really good", "not really", "really want", "really appreciate"],
  },
  {
    id: "well",
    rank: 61,
    type: "word",
    term: "well",
    ipa: "/wel/",
    pos: "adverb/interjection",
    meanings: ["うまく", "さて", "ええと"],
    core: "状態が整っている、または発話を整える。",
    usage: ["良い状態、健康、話し始めの間に使う。", "Well, ... は答えを少し整えてから出す合図。"],
    examples: [
      ["That went well.", "うまくいったね。"],
      ["Well, I think you're right.", "ええと、君が正しいと思う。"],
    ],
    chunks: ["as well", "well done", "get well", "well then"],
  },
  {
    id: "now",
    rank: 62,
    type: "word",
    term: "now",
    ipa: "/naʊ/",
    pos: "adverb",
    meanings: ["今", "さあ", "今では"],
    core: "時間の焦点を現在へ合わせる。",
    usage: ["現在、すぐ、話題転換に使う。", "right now は今この瞬間を強める。"],
    examples: [
      ["I'm busy right now.", "今ちょっと忙しい。"],
      ["Now I understand.", "今わかった。"],
    ],
    chunks: ["right now", "now that", "from now on"],
  },
  {
    id: "then",
    rank: 63,
    type: "word",
    term: "then",
    ipa: "/ðen/",
    pos: "adverb",
    meanings: ["その時", "それから", "では"],
    core: "前の時点や条件の次に進める。",
    usage: ["順序、結果、条件からの結論に使う。", "See you then は約束した時を受ける。"],
    examples: [
      ["I'll see you then.", "その時に会おう。"],
      ["If you're ready, then let's start.", "準備ができたなら始めよう。"],
    ],
    chunks: ["and then", "back then", "by then", "then again"],
  },
  {
    id: "more",
    rank: 64,
    type: "word",
    term: "more",
    ipa: "/mɔːr/",
    pos: "determiner/adverb",
    meanings: ["もっと", "さらに", "より多く"],
    core: "今ある量や程度をもう一段増やす。",
    usage: ["量、程度、比較に使う。", "one more は会話でとても使いやすい。"],
    examples: [
      ["Can I have one more?", "もう一つもらえる？"],
      ["Tell me more about it.", "それについてもっと教えて。"],
    ],
    chunks: ["one more", "more than", "no more", "more like"],
  },
  {
    id: "no",
    rank: 65,
    type: "word",
    term: "no",
    ipa: "/noʊ/",
    pos: "determiner/interjection",
    meanings: ["いいえ", "まったくない", "禁止"],
    core: "選択肢や存在をはっきり閉じる。",
    usage: ["返答、数量ゼロ、否定の強調に使う。", "No worries は軽い返答として自然。"],
    examples: [
      ["No, that's okay.", "いや、大丈夫。"],
      ["I have no idea.", "まったくわからない。"],
    ],
    chunks: ["no problem", "no worries", "no idea", "no way"],
  },
  {
    id: "up",
    rank: 66,
    type: "word",
    term: "up",
    ipa: "/ʌp/",
    pos: "adverb",
    meanings: ["上へ", "完全に", "起きて"],
    core: "上方向、または状態を立ち上げて完了へ向ける。",
    usage: ["方向、増加、完了、準備に使う。", "What's up? は近況を聞く軽い挨拶。"],
    examples: [
      ["What's up?", "どうしたの？元気？"],
      ["I'll clean up later.", "あとで片づけるよ。"],
    ],
    chunks: ["pick up", "wake up", "show up", "clean up"],
  },
  {
    id: "people",
    rank: 67,
    type: "word",
    term: "people",
    ipa: "/ˈpiːpəl/",
    pos: "noun",
    meanings: ["人々", "みんな"],
    core: "個人をまとめて、人の集まりとして見る。",
    usage: ["一般の人々、特定グループ、民族に使う。", "many people より a lot of people が会話では自然なことが多い。"],
    examples: [
      ["A lot of people say that.", "多くの人がそう言う。"],
      ["People change.", "人は変わるものだ。"],
    ],
    chunks: ["a lot of people", "some people", "people like us"],
  },
  {
    id: "good",
    rank: 68,
    type: "word",
    term: "good",
    ipa: "/ɡʊd/",
    pos: "adjective",
    meanings: ["良い", "上手な", "十分な"],
    core: "目的や期待に合っていて、前向きに評価できる。",
    usage: ["品質、状態、能力、了承に使う。", "I'm good は断る時にも「大丈夫です」と使える。"],
    examples: [
      ["Sounds good.", "いいね。"],
      ["I'm good, thanks.", "大丈夫です、ありがとう。"],
    ],
    chunks: ["good at", "good for", "sounds good", "a good one"],
  },
  {
    id: "because",
    rank: 69,
    type: "word",
    term: "because",
    ipa: "/bɪˈkɔːz, bɪˈkʌz/",
    pos: "conjunction",
    meanings: ["なぜなら", "〜だから"],
    core: "出来事の後ろにある理由をつなげる。",
    usage: ["理由を明示する。", "because of の後ろには名詞を置く。"],
    examples: [
      ["I stayed home because I was sick.", "具合が悪かったので家にいた。"],
      ["Because of the rain, we canceled it.", "雨のせいで中止した。"],
    ],
    chunks: ["because of", "just because", "that's because"],
  },
  {
    id: "how",
    rank: 70,
    type: "word",
    term: "how",
    ipa: "/haʊ/",
    pos: "adverb",
    meanings: ["どう", "どのくらい", "なんて"],
    core: "方法・状態・程度の空欄をたずねる。",
    usage: ["方法、状態、程度、感嘆に使う。", "How about ...? は提案の定番。"],
    examples: [
      ["How are you doing?", "調子はどう？"],
      ["How did you know?", "どうしてわかったの？"],
    ],
    chunks: ["how about", "how much", "how long", "how come"],
  },
  {
    id: "kind-of",
    rank: 71,
    type: "phrase",
    term: "kind of",
    ipa: "/ˈkaɪnd əv, ˈkaɪnə/",
    pos: "phrase",
    meanings: ["ちょっと", "ある種の", "なんとなく"],
    core: "はっきり断定せず、近い種類や程度にぼかす。",
    usage: ["形容詞や感想を弱める。", "会話では kinda /ˈkaɪndə/ と短くなる。"],
    examples: [
      ["I'm kind of nervous.", "ちょっと緊張してる。"],
      ["It's kind of hard to explain.", "説明するのがちょっと難しい。"],
    ],
    chunks: ["kinda", "kind of like", "kind of hard"],
  },
  {
    id: "a-lot-of",
    rank: 72,
    type: "phrase",
    term: "a lot of",
    ipa: "/ə ˈlɑːt əv/",
    pos: "phrase",
    meanings: ["たくさんの", "多くの"],
    core: "量や数がまとまって多いことを、自然な会話の形で出す。",
    usage: ["数えられる名詞にも数えられない名詞にも使える。", "会話では many / much より柔らかいことが多い。"],
    examples: [
      ["I have a lot of work today.", "今日は仕事がたくさんある。"],
      ["A lot of people liked it.", "多くの人がそれを気に入った。"],
    ],
    chunks: ["a lot of time", "a lot of people", "thanks a lot"],
  },
  {
    id: "you-know",
    rank: 73,
    type: "phrase",
    term: "you know",
    ipa: "/jə ˈnoʊ/",
    pos: "phrase",
    meanings: ["ほら", "わかるでしょ", "えっと"],
    core: "相手と共有している感覚に軽く橋をかける。",
    usage: ["確認、間つなぎ、共感づくりに使う。", "使いすぎると口癖っぽく聞こえる。"],
    examples: [
      ["It was, you know, a little awkward.", "それは、ほら、ちょっと気まずかった。"],
      ["You know what I mean?", "言いたいことわかる？"],
    ],
    chunks: ["you know what", "you know what I mean"],
  },
  {
    id: "i-mean",
    rank: 74,
    type: "phrase",
    term: "I mean",
    ipa: "/aɪ ˈmiːn/",
    pos: "phrase",
    meanings: ["つまり", "いや", "というか"],
    core: "自分の言葉を言い直して、狙った意味に寄せる。",
    usage: ["訂正、補足、言い換え、ためらいに使う。", "強く言うと「本気で言っている」の意味にもなる。"],
    examples: [
      ["I mean, it's not impossible.", "つまり、不可能ではないよ。"],
      ["I didn't mean it that way.", "そういう意味で言ったんじゃない。"],
    ],
    chunks: ["what I mean", "I mean it", "you mean"],
  },
  {
    id: "have-to",
    rank: 75,
    type: "phrase",
    term: "have to",
    ipa: "/ˈhæv tə, ˈhæf tə/",
    pos: "phrase",
    meanings: ["〜しなければならない"],
    core: "外側の事情として、必要性を自分が抱えている。",
    usage: ["義務、必要、避けられない予定に使う。", "has to は /ˈhæz tə/ または /ˈhæs tə/。"],
    examples: [
      ["I have to get up early.", "早起きしなきゃ。"],
      ["You don't have to decide now.", "今決めなくてもいいよ。"],
    ],
    chunks: ["don't have to", "have to go", "have to be"],
  },
  {
    id: "want-to",
    rank: 76,
    type: "phrase",
    term: "want to",
    ipa: "/ˈwɑːnt tə, ˈwɑːnə/",
    pos: "phrase",
    meanings: ["〜したい"],
    core: "心がある行動へ向かっている。",
    usage: ["希望や誘いに使う。", "wanna はカジュアルな会話形。"],
    examples: [
      ["I want to learn this properly.", "これをちゃんと学びたい。"],
      ["Do you want to join us?", "一緒に来る？"],
    ],
    chunks: ["wanna", "want to be", "want to know"],
  },
  {
    id: "let-me",
    rank: 77,
    type: "phrase",
    term: "let me",
    ipa: "/ˈlet mi/",
    pos: "phrase",
    meanings: ["私に〜させて", "〜するね"],
    core: "自分が動く余地を相手に開けてもらう。",
    usage: ["申し出、確認、提案の前に置く。", "Let me know は知らせて、Let me see は考えさせて。"],
    examples: [
      ["Let me know when you're free.", "空いている時を教えて。"],
      ["Let me think about it.", "それについて考えさせて。"],
    ],
    chunks: ["let me know", "let me see", "let me check"],
  },
  {
    id: "go-ahead",
    rank: 78,
    type: "phrase",
    term: "go ahead",
    ipa: "/ˌɡoʊ əˈhed/",
    pos: "phrase",
    meanings: ["どうぞ", "先に進む", "始める"],
    core: "前に進む許可を出す。",
    usage: ["相手に許可する、先に行く、実行する時に使う。", "Please go ahead. は丁寧な「どうぞ」。"],
    examples: [
      ["Can I ask a question? Go ahead.", "質問していい？どうぞ。"],
      ["Go ahead and start without me.", "私なしで先に始めて。"],
    ],
    chunks: ["go right ahead", "go ahead and"],
  },
  {
    id: "make-sure",
    rank: 79,
    type: "phrase",
    term: "make sure",
    ipa: "/ˌmeɪk ˈʃʊr/",
    pos: "phrase",
    meanings: ["必ず確認する", "確実にする"],
    core: "曖昧な状態を、間違いない形に作る。",
    usage: ["確認、念押し、準備に使う。", "Make sure to ... は「必ず〜して」。"],
    examples: [
      ["Make sure you lock the door.", "必ずドアに鍵をかけて。"],
      ["I just want to make sure.", "念のため確認したいだけ。"],
    ],
    chunks: ["make sure to", "just to make sure"],
  },
  {
    id: "by-the-way",
    rank: 80,
    type: "phrase",
    term: "by the way",
    ipa: "/ˌbaɪ ðə ˈweɪ/",
    pos: "phrase",
    meanings: ["ところで", "ちなみに"],
    core: "本筋の道の横から、別の話題を差し込む。",
    usage: ["話題転換や補足を自然に始める。", "BTW はチャットでよく使う略。"],
    examples: [
      ["By the way, are you free tomorrow?", "ところで、明日空いてる？"],
      ["By the way, I liked your presentation.", "ちなみに、君の発表よかったよ。"],
    ],
    chunks: ["oh, by the way", "btw"],
  },
];
