window.GACHI_ENTRIES = [
  {
    id: "the",
    rank: 1,
    type: "word",
    term: "the",
    ipa: "/ðə, ði/",
    pos: "article",
    meanings: ["その", "例の", "共通認識のもの"],
    core: "話し手と聞き手が同じものを指せるように、名詞へ小さなスポットライトを当てる。",
    usage: ["すでに出たもの、場にあるもの、唯一だとわかるものに付く。", "母音の前や強調では /ði/ になりやすい。"],
    examples: [
      ["Can you close the door?", "そのドアを閉めてくれる？"],
      ["The thing is, I forgot my phone.", "問題は、携帯を忘れたってことなんだ。"],
    ],
    chunks: ["the thing is", "the same", "the other day"],
  },
  {
    id: "i",
    rank: 2,
    type: "word",
    term: "I",
    ipa: "/aɪ/",
    pos: "pronoun",
    meanings: ["私は", "自分は"],
    core: "話し手である自分を、会話の出発点として置く。",
    usage: ["意見、気持ち、経験を出すときの基本の主語。", "会話では I think, I mean, I guess が非常に多い。"],
    examples: [
      ["I think we should wait.", "待ったほうがいいと思う。"],
      ["I didn't know that.", "それは知らなかった。"],
    ],
    chunks: ["I think", "I mean", "I guess", "I don't know"],
  },
  {
    id: "you",
    rank: 3,
    type: "word",
    term: "you",
    ipa: "/juː, jə/",
    pos: "pronoun",
    meanings: ["あなた", "みんな", "一般に人は"],
    core: "目の前の相手、または人一般へ視点を向ける。",
    usage: ["相手を直接指すほか、一般論の you もよく使う。", "弱く読むと /jə/ に近くなる。"],
    examples: [
      ["Do you want some coffee?", "コーヒーいる？"],
      ["You never know.", "何が起きるかわからないよ。"],
    ],
    chunks: ["you know", "you mean", "do you want", "thank you"],
  },
  {
    id: "be",
    rank: 4,
    type: "word",
    term: "be",
    ipa: "/biː/",
    pos: "verb",
    meanings: ["ある", "いる", "〜である"],
    core: "人や物を、ある状態・場所・役割にそっと置く。",
    usage: ["am, are, is, was, were などに形を変える。", "存在、状態、進行形、受け身の土台になる。"],
    examples: [
      ["I'll be there in ten minutes.", "10分でそこに着くよ。"],
      ["It's going to be fine.", "きっとうまくいくよ。"],
    ],
    chunks: ["be right back", "be careful", "be into"],
  },
  {
    id: "to",
    rank: 5,
    type: "word",
    term: "to",
    ipa: "/tuː, tə/",
    pos: "preposition",
    meanings: ["〜へ", "〜に", "〜するために"],
    core: "ある地点・相手・目的へ向かう矢印。",
    usage: ["方向、到達点、受け手、目的を表す。", "不定詞では動作へ向かう感じを作る。"],
    examples: [
      ["I'm going to the store.", "店に行くところ。"],
      ["I need to talk to you.", "君に話す必要がある。"],
    ],
    chunks: ["have to", "want to", "talk to", "go to"],
  },
  {
    id: "and",
    rank: 6,
    type: "word",
    term: "and",
    ipa: "/ænd, ən/",
    pos: "conjunction",
    meanings: ["そして", "〜と", "それに"],
    core: "要素を横につなげて、流れを続ける接着剤。",
    usage: ["単語、文、出来事を自然につなげる。", "会話では弱く /ən/ のように聞こえやすい。"],
    examples: [
      ["Come in and sit down.", "入って座って。"],
      ["I called and left a message.", "電話してメッセージを残した。"],
    ],
    chunks: ["and then", "and so", "you and me"],
  },
  {
    id: "a",
    rank: 7,
    type: "word",
    term: "a / an",
    ipa: "/ə, ən/",
    pos: "article",
    meanings: ["ひとつの", "ある", "種類としての"],
    core: "輪郭のある一つを、たくさんある中から軽く取り出す。",
    usage: ["初めて出す名詞や、職業・種類を言うときに使う。", "母音の音の前では an。つづりではなく音で決まる。"],
    examples: [
      ["I need a minute.", "少し時間が必要。"],
      ["She's an engineer.", "彼女はエンジニアです。"],
    ],
    chunks: ["a little", "a lot", "a couple of"],
  },
  {
    id: "it",
    rank: 8,
    type: "word",
    term: "it",
    ipa: "/ɪt/",
    pos: "pronoun",
    meanings: ["それ", "状況", "時間・天気の主語"],
    core: "話題になっている物事や状況を、小さく受け止める代名詞。",
    usage: ["物、状況、前の文全体を受ける。", "It's ... で天気・時間・感想をすばやく言える。"],
    examples: [
      ["It sounds good.", "よさそうだね。"],
      ["I can do it.", "それできるよ。"],
    ],
    chunks: ["it's okay", "that's it", "make it", "it depends"],
  },
  {
    id: "that",
    rank: 9,
    type: "word",
    term: "that",
    ipa: "/ðæt/",
    pos: "determiner",
    meanings: ["あれ", "それ", "〜ということ"],
    core: "少し離れたものや、まとめた内容を指差す。",
    usage: ["名詞の前では「あの」、単独では「それ」。", "文を受けて「それは」と言うときに強い。"],
    examples: [
      ["That's exactly what I mean.", "まさにそれが言いたいこと。"],
      ["I didn't know that you were here.", "君がここにいるとは知らなかった。"],
    ],
    chunks: ["that's why", "like that", "that makes sense"],
  },
  {
    id: "of",
    rank: 10,
    type: "word",
    term: "of",
    ipa: "/əv, ʌv/",
    pos: "preposition",
    meanings: ["〜の", "〜から成る", "〜について"],
    core: "全体と部分、持ち主と中身をゆるく結びつける。",
    usage: ["日本語の「の」に近いが、材料・所属・内容にも広い。", "a lot of, kind of など会話の塊で覚えると強い。"],
    examples: [
      ["A friend of mine lives here.", "私の友人がここに住んでいる。"],
      ["I'm kind of tired.", "ちょっと疲れてる。"],
    ],
    chunks: ["a lot of", "kind of", "out of", "because of"],
  },
  {
    id: "in",
    rank: 11,
    type: "word",
    term: "in",
    ipa: "/ɪn/",
    pos: "preposition",
    meanings: ["〜の中に", "〜で", "〜後に"],
    core: "空間・時間・状況の中に入っている感覚。",
    usage: ["場所、期間、状態、分野の内側を表す。", "in a minute のように未来の時間にも使う。"],
    examples: [
      ["I'll be there in five minutes.", "5分後に行くよ。"],
      ["She's in a meeting.", "彼女は会議中です。"],
    ],
    chunks: ["in case", "in front of", "in the middle of"],
  },
  {
    id: "is",
    rank: 12,
    type: "word",
    term: "is",
    ipa: "/ɪz, z/",
    pos: "verb",
    meanings: ["〜です", "〜にいる", "〜である"],
    core: "一つの主語を、今の状態や場所に結びつける。",
    usage: ["he, she, it, 単数名詞の現在に使う。", "会話では it's, that's, he's の形で頻出。"],
    examples: [
      ["It's not a big deal.", "大したことじゃないよ。"],
      ["Where is everyone?", "みんなどこ？"],
    ],
    chunks: ["it is", "that is", "where is", "is there"],
  },
  {
    id: "for",
    rank: 13,
    type: "word",
    term: "for",
    ipa: "/fɔːr, fər/",
    pos: "preposition",
    meanings: ["〜のために", "〜に向けて", "〜の間"],
    core: "利益・目的・期間へ向かって差し出す感じ。",
    usage: ["相手の利益、目的、理由、期間を表す。", "Thanks for ... で感謝の理由を置く。"],
    examples: [
      ["This is for you.", "これは君に。"],
      ["Thanks for helping me.", "手伝ってくれてありがとう。"],
    ],
    chunks: ["for now", "for sure", "look for", "wait for"],
  },
  {
    id: "we",
    rank: 14,
    type: "word",
    term: "we",
    ipa: "/wiː/",
    pos: "pronoun",
    meanings: ["私たちは", "こちらは"],
    core: "話し手を含むグループを一つにまとめる。",
    usage: ["相手を含む場合と含まない場合がある。", "提案では Should we ...? が自然。"],
    examples: [
      ["We should talk later.", "あとで話したほうがいいね。"],
      ["Are we good?", "これで大丈夫？"],
    ],
    chunks: ["we need to", "should we", "are we good"],
  },
  {
    id: "on",
    rank: 15,
    type: "word",
    term: "on",
    ipa: "/ɑːn/",
    pos: "preposition",
    meanings: ["〜の上に", "〜中で", "〜に接して"],
    core: "表面や流れに接触している感じ。",
    usage: ["場所、曜日、機器の稼働、話題への接触を表す。", "on time は決まった時刻に接しているイメージ。"],
    examples: [
      ["I'm on my way.", "今向かってる。"],
      ["Let's talk on Monday.", "月曜に話そう。"],
    ],
    chunks: ["on time", "on my way", "on the phone"],
  },
  {
    id: "do",
    rank: 16,
    type: "word",
    term: "do",
    ipa: "/duː, də/",
    pos: "verb",
    meanings: ["する", "行う", "疑問・否定を作る"],
    core: "何かを実行する、または文を動かすためのエンジン。",
    usage: ["一般動詞の疑問文・否定文を作る。", "Do you ...? は会話の入口として非常に多い。"],
    examples: [
      ["What do you do?", "仕事は何をしているの？"],
      ["I don't think so.", "そうは思わない。"],
    ],
    chunks: ["do you", "don't", "do that", "what do you mean"],
  },
  {
    id: "have",
    rank: 17,
    type: "word",
    term: "have",
    ipa: "/hæv, həv/",
    pos: "verb",
    meanings: ["持っている", "食べる", "経験する"],
    core: "自分の領域の中に、物・時間・経験を持つ。",
    usage: ["所有だけでなく、予定・経験・食事にも使う。", "have to は外から来る必要性を持っている感じ。"],
    examples: [
      ["I have a question.", "質問があります。"],
      ["We have to leave now.", "もう出ないといけない。"],
    ],
    chunks: ["have to", "have a good one", "have no idea"],
  },
  {
    id: "not",
    rank: 18,
    type: "word",
    term: "not",
    ipa: "/nɑːt/",
    pos: "adverb",
    meanings: ["〜でない", "〜しない"],
    core: "文の内容にストップをかけて、否定へ反転させる。",
    usage: ["be動詞・助動詞の後ろに置く。", "not really は柔らかい否定としてよく使う。"],
    examples: [
      ["I'm not sure.", "よくわからない。"],
      ["Not really.", "そうでもないかな。"],
    ],
    chunks: ["not sure", "not really", "not at all"],
  },
  {
    id: "this",
    rank: 19,
    type: "word",
    term: "this",
    ipa: "/ðɪs/",
    pos: "determiner",
    meanings: ["これ", "この", "今の"],
    core: "手元・目の前・今ここにあるものを指差す。",
    usage: ["近い物、今の状況、これから言う内容を示す。", "This is ... は紹介や説明の基本形。"],
    examples: [
      ["This is really good.", "これ本当においしい。"],
      ["I can't do this right now.", "今これはできない。"],
    ],
    chunks: ["this one", "this time", "this is it"],
  },
  {
    id: "but",
    rank: 20,
    type: "word",
    term: "but",
    ipa: "/bʌt, bət/",
    pos: "conjunction",
    meanings: ["でも", "しかし", "ただ"],
    core: "前の流れに小さなブレーキをかけて、別方向へ曲げる。",
    usage: ["反対、例外、遠慮した言い足しに使う。", "会話では文頭の But ... も自然。"],
    examples: [
      ["I like it, but it's expensive.", "好きだけど高いね。"],
      ["Sorry, but I have to go.", "ごめん、でも行かないと。"],
    ],
    chunks: ["but still", "but then", "sorry but"],
  },
  {
    id: "what",
    rank: 21,
    type: "word",
    term: "what",
    ipa: "/wʌt, wət/",
    pos: "pronoun",
    meanings: ["何", "どんなもの", "〜すること"],
    core: "わからない中身を空欄として差し出す。",
    usage: ["情報をたずねる基本語。", "What about ...? で話題を向ける。"],
    examples: [
      ["What are you doing?", "何してるの？"],
      ["What about tomorrow?", "明日はどう？"],
    ],
    chunks: ["what if", "what about", "what do you mean"],
  },
  {
    id: "so",
    rank: 22,
    type: "word",
    term: "so",
    ipa: "/soʊ/",
    pos: "adverb",
    meanings: ["だから", "とても", "そう"],
    core: "前の内容を受けて、結果や程度を押し出す。",
    usage: ["理由から結果へ進める。", "so good のように程度を強める。"],
    examples: [
      ["I was tired, so I went home.", "疲れていたので帰った。"],
      ["That's so nice of you.", "それは本当に親切だね。"],
    ],
    chunks: ["so far", "so much", "so that", "and so"],
  },
  {
    id: "get",
    rank: 23,
    type: "word",
    term: "get",
    ipa: "/ɡet/",
    pos: "verb",
    meanings: ["得る", "着く", "わかる", "〜になる"],
    core: "動いて、何かを自分の側に取り込む。",
    usage: ["物を手に入れる、場所に着く、状態になる、理解する。", "会話では get it, get to, get ready が多い。"],
    examples: [
      ["I get it now.", "今わかった。"],
      ["Let's get some lunch.", "昼ごはんを食べよう。"],
    ],
    chunks: ["get it", "get to", "get ready", "get along"],
  },
  {
    id: "can",
    rank: 24,
    type: "word",
    term: "can",
    ipa: "/kæn, kən/",
    pos: "modal verb",
    meanings: ["できる", "してもよい", "あり得る"],
    core: "可能性や許可のドアが開いている。",
    usage: ["能力、依頼、許可、可能性を表す。", "Can you ...? は依頼の定番。"],
    examples: [
      ["Can you help me?", "手伝ってくれる？"],
      ["It can happen to anyone.", "誰にでも起こり得るよ。"],
    ],
    chunks: ["can I", "can you", "I can't", "can't wait"],
  },
  {
    id: "just",
    rank: 25,
    type: "word",
    term: "just",
    ipa: "/dʒʌst/",
    pos: "adverb",
    meanings: ["ただ", "ちょうど", "ほんの", "今さっき"],
    core: "範囲を細く絞って、余計なものを外す。",
    usage: ["軽くする、限定する、時間の近さを出す。", "Just a second. は会話で非常に便利。"],
    examples: [
      ["Just give me a second.", "ちょっとだけ待って。"],
      ["I just got here.", "今着いたばかり。"],
    ],
    chunks: ["just a sec", "just in case", "just like"],
  },
  {
    id: "like",
    rank: 26,
    type: "word",
    term: "like",
    ipa: "/laɪk/",
    pos: "verb/preposition",
    meanings: ["好き", "〜のような", "例えば"],
    core: "心が近づく、または形や感じが近いものへ寄せる。",
    usage: ["好み、類似、例示、口語のつなぎに使う。", "Would you like ...? は丁寧な申し出。"],
    examples: [
      ["I like the way you said that.", "その言い方いいね。"],
      ["It's like five minutes away.", "5分くらいの距離だよ。"],
    ],
    chunks: ["feel like", "look like", "would like", "like this"],
  },
  {
    id: "know",
    rank: 27,
    type: "word",
    term: "know",
    ipa: "/noʊ/",
    pos: "verb",
    meanings: ["知っている", "わかっている"],
    core: "情報や人が、自分の中でつながっている状態。",
    usage: ["知識、認識、人との面識に使う。", "I don't know は会話の超頻出形。"],
    examples: [
      ["Do you know where she is?", "彼女がどこにいるか知ってる？"],
      ["I know what you mean.", "言いたいことはわかるよ。"],
    ],
    chunks: ["you know", "I know", "don't know", "let me know"],
  },
  {
    id: "go",
    rank: 28,
    type: "word",
    term: "go",
    ipa: "/ɡoʊ/",
    pos: "verb",
    meanings: ["行く", "進む", "うまくいく"],
    core: "今いる場所や状態から、別の方向へ進む。",
    usage: ["移動、進行、予定、状態の変化に使う。", "How's it going? は挨拶でよく使う。"],
    examples: [
      ["I have to go.", "行かなきゃ。"],
      ["How did it go?", "どうだった？"],
    ],
    chunks: ["go ahead", "go for it", "go with", "going to"],
  },
  {
    id: "was",
    rank: 29,
    type: "word",
    term: "was",
    ipa: "/wʌz, wəz/",
    pos: "verb",
    meanings: ["〜だった", "〜にいた"],
    core: "過去の一点で、主語を状態や場所に置く。",
    usage: ["I, he, she, it, 単数名詞の過去に使う。", "会話では I was like ... で当時の反応を言える。"],
    examples: [
      ["I was busy yesterday.", "昨日は忙しかった。"],
      ["That was really helpful.", "それは本当に助かった。"],
    ],
    chunks: ["I was like", "that was", "was going to"],
  },
  {
    id: "my",
    rank: 30,
    type: "word",
    term: "my",
    ipa: "/maɪ/",
    pos: "determiner",
    meanings: ["私の"],
    core: "物や人を、自分の領域にあるものとして示す。",
    usage: ["所有だけでなく、関係・担当・経験にも使う。", "my bad はカジュアルな謝罪。"],
    examples: [
      ["My phone is dead.", "携帯の充電が切れた。"],
      ["My bad. I forgot.", "ごめん、忘れてた。"],
    ],
    chunks: ["my bad", "my turn", "my point is"],
  },
  {
    id: "will",
    rank: 31,
    type: "word",
    term: "will",
    ipa: "/wɪl, əl/",
    pos: "modal verb",
    meanings: ["〜するつもり", "〜だろう"],
    core: "これから先へ向かう意志や見込みを置く。",
    usage: ["その場で決める未来、予測、約束に使う。", "I'll ... は会話で最も軽い約束形の一つ。"],
    examples: [
      ["I will call you later.", "あとで電話するね。"],
      ["It'll be okay.", "大丈夫だよ。"],
    ],
    chunks: ["I'll", "we'll", "will be", "will do"],
  },
  {
    id: "all",
    rank: 32,
    type: "word",
    term: "all",
    ipa: "/ɔːl/",
    pos: "determiner",
    meanings: ["すべて", "全員", "まったく"],
    core: "残りなく全体を包み込む。",
    usage: ["全体、全員、強調に使う。", "all right は了承・状態・間投詞として頻出。"],
    examples: [
      ["That's all I need.", "必要なのはそれだけ。"],
      ["Are you all right?", "大丈夫？"],
    ],
    chunks: ["all right", "all the time", "after all", "that's all"],
  },
  {
    id: "there",
    rank: 33,
    type: "word",
    term: "there",
    ipa: "/ðer/",
    pos: "adverb",
    meanings: ["そこに", "存在を示す"],
    core: "自分から少し離れた場所、または存在の場を指す。",
    usage: ["場所を示すほか、There is/are で存在を出す。", "there you go は渡す・完了・理解の合図。"],
    examples: [
      ["There's one more thing.", "もう一つある。"],
      ["I'll meet you there.", "そこで会おう。"],
    ],
    chunks: ["there is", "there are", "there you go", "over there"],
  },
  {
    id: "one",
    rank: 34,
    type: "word",
    term: "one",
    ipa: "/wʌn/",
    pos: "number/pronoun",
    meanings: ["一つ", "もの", "人"],
    core: "まとまりを一つとして数えたり、前の名詞を受けたりする。",
    usage: ["数字だけでなく、one more, this one のように代名詞で使う。", "someone, anyone などの核にもなる。"],
    examples: [
      ["Can I have one?", "一つもらっていい？"],
      ["This one is better.", "こっちのほうがいい。"],
    ],
    chunks: ["one more", "this one", "no one", "the one"],
  },
  {
    id: "about",
    rank: 35,
    type: "word",
    term: "about",
    ipa: "/əˈbaʊt/",
    pos: "preposition/adverb",
    meanings: ["〜について", "だいたい", "〜の周りに"],
    core: "話題や数値の周辺をぐるっと囲む。",
    usage: ["話題、概算、周辺性を表す。", "How about ...? で提案や確認に使う。"],
    examples: [
      ["What are you talking about?", "何の話をしてるの？"],
      ["How about Friday?", "金曜はどう？"],
    ],
    chunks: ["how about", "what about", "about to", "talk about"],
  },
  {
    id: "out",
    rank: 36,
    type: "word",
    term: "out",
    ipa: "/aʊt/",
    pos: "adverb",
    meanings: ["外へ", "切れて", "終わって"],
    core: "内側から外側へ出る、または範囲から外れる。",
    usage: ["場所の外、在庫切れ、完了、公開に使う。", "find out は外へ取り出して知るイメージ。"],
    examples: [
      ["Let's go out tonight.", "今夜出かけよう。"],
      ["I found out yesterday.", "昨日わかった。"],
    ],
    chunks: ["out of", "find out", "check out", "work out"],
  },
  {
    id: "if",
    rank: 37,
    type: "word",
    term: "if",
    ipa: "/ɪf/",
    pos: "conjunction",
    meanings: ["もし", "〜かどうか"],
    core: "まだ確定していない条件の扉を開く。",
    usage: ["条件、仮定、確認の間接疑問に使う。", "What if ...? で可能性を投げる。"],
    examples: [
      ["If you're free, call me.", "空いてたら電話して。"],
      ["I don't know if I can go.", "行けるかどうかわからない。"],
    ],
    chunks: ["what if", "if you want", "if so", "even if"],
  },
  {
    id: "me",
    rank: 38,
    type: "word",
    term: "me",
    ipa: "/miː/",
    pos: "pronoun",
    meanings: ["私を", "私に"],
    core: "動作や影響を受ける自分。",
    usage: ["目的語として使う。", "Let me ... は自分が何かする許可や提案。"],
    examples: [
      ["Let me check.", "確認するね。"],
      ["Can you send it to me?", "それを送ってくれる？"],
    ],
    chunks: ["let me", "tell me", "with me", "for me"],
  },
  {
    id: "your",
    rank: 39,
    type: "word",
    term: "your",
    ipa: "/jʊr, jər/",
    pos: "determiner",
    meanings: ["あなたの", "あなたたちの"],
    core: "相手の領域に属するものとして示す。",
    usage: ["所有、関係、担当、意見に使う。", "What's your ...? は会話開始に強い。"],
    examples: [
      ["What's your name?", "名前は何ですか？"],
      ["I like your idea.", "君のアイデアいいね。"],
    ],
    chunks: ["your turn", "your call", "your place"],
  },
  {
    id: "going-to",
    rank: 40,
    type: "phrase",
    term: "going to",
    ipa: "/ˈɡoʊɪŋ tə, ˈɡənə/",
    pos: "phrase",
    meanings: ["〜する予定", "〜になりそう"],
    core: "すでにそちらへ向かって動き出している未来。",
    usage: ["予定や根拠のある未来を表す。", "会話では gonna /ˈɡənə/ と縮みやすい。"],
    examples: [
      ["I'm going to call her.", "彼女に電話するつもり。"],
      ["It's going to rain.", "雨が降りそう。"],
    ],
    chunks: ["I'm gonna", "are you gonna", "going to be"],
  },
  {
    id: "they",
    rank: 41,
    type: "word",
    term: "they",
    ipa: "/ðeɪ/",
    pos: "pronoun",
    meanings: ["彼らは", "それらは", "その人は"],
    core: "自分と相手から離れた複数、または性別を特定しない人を指す。",
    usage: ["人・物の複数を受ける。", "単数の they は性別不明・不特定の人にも使われる。"],
    examples: [
      ["They said it was okay.", "大丈夫だと言っていたよ。"],
      ["Someone left their bag here.", "誰かがバッグをここに置いていった。"],
    ],
    chunks: ["they say", "they are", "they have"],
  },
  {
    id: "say",
    rank: 42,
    type: "word",
    term: "say",
    ipa: "/seɪ/",
    pos: "verb",
    meanings: ["言う", "書いてある", "仮に〜とする"],
    core: "言葉や情報を外へ出す。",
    usage: ["発言、表示、提案、仮定に使う。", "What did you say? は聞き返しの基本。"],
    examples: [
      ["What did she say?", "彼女は何て言った？"],
      ["Let's say we leave at six.", "6時に出るとしよう。"],
    ],
    chunks: ["say that", "let's say", "I would say"],
  },
  {
    id: "would",
    rank: 43,
    type: "word",
    term: "would",
    ipa: "/wʊd, əd/",
    pos: "modal verb",
    meanings: ["〜だろう", "〜してくれる", "〜したものだった"],
    core: "現実から少し距離を置いて、やわらかく可能性を出す。",
    usage: ["丁寧な依頼、仮定、過去の習慣に使う。", "I'd like ... は丁寧な希望。"],
    examples: [
      ["Would you mind opening the window?", "窓を開けてもらえますか？"],
      ["I would do the same thing.", "私も同じことをすると思う。"],
    ],
    chunks: ["would like", "would you", "I would", "that would be"],
  },
  {
    id: "as",
    rank: 44,
    type: "word",
    term: "as",
    ipa: "/æz, əz/",
    pos: "conjunction/preposition",
    meanings: ["〜として", "〜のように", "〜するとき"],
    core: "二つのものを同じ線上に並べる。",
    usage: ["役割、同時性、比較、理由に使う。", "as soon as で「〜したらすぐ」。"],
    examples: [
      ["Use this as a guide.", "これをガイドとして使って。"],
      ["As soon as I get home, I'll call you.", "家に着いたらすぐ電話する。"],
    ],
    chunks: ["as soon as", "as well", "as long as", "as if"],
  },
  {
    id: "at",
    rank: 45,
    type: "word",
    term: "at",
    ipa: "/æt, ət/",
    pos: "preposition",
    meanings: ["〜で", "〜に", "〜をめがけて"],
    core: "一点にピンを刺す。",
    usage: ["時刻、地点、対象への狙いを表す。", "at least, at all など塊で多い。"],
    examples: [
      ["Let's meet at seven.", "7時に会おう。"],
      ["I'm good at cooking.", "料理が得意です。"],
    ],
    chunks: ["at least", "at all", "at home", "look at"],
  },
  {
    id: "or",
    rank: 46,
    type: "word",
    term: "or",
    ipa: "/ɔːr, ər/",
    pos: "conjunction",
    meanings: ["または", "それとも", "つまり"],
    core: "選択肢を横に並べて、どちらかへ分ける。",
    usage: ["選択、言い換え、否定文の列挙に使う。", "or something はぼかしとして頻出。"],
    examples: [
      ["Do you want coffee or tea?", "コーヒーか紅茶いる？"],
      ["Call me or send a text.", "電話かメッセージして。"],
    ],
    chunks: ["or not", "or something", "sooner or later"],
  },
  {
    id: "are",
    rank: 47,
    type: "word",
    term: "are",
    ipa: "/ɑːr, ər/",
    pos: "verb",
    meanings: ["〜です", "〜にいる"],
    core: "複数や you を、今の状態・場所に置く。",
    usage: ["you, we, they, 複数名詞の現在に使う。", "How are you? の核。"],
    examples: [
      ["Are you ready?", "準備できた？"],
      ["We are almost there.", "もうすぐ着くよ。"],
    ],
    chunks: ["are you", "we are", "they are", "how are"],
  },
  {
    id: "from",
    rank: 48,
    type: "word",
    term: "from",
    ipa: "/frʌm, frəm/",
    pos: "preposition",
    meanings: ["〜から", "〜出身", "〜によって"],
    core: "出発点や源を示す。",
    usage: ["場所、時点、原因、材料、出身に使う。", "hear from は相手から連絡が来る感じ。"],
    examples: [
      ["Where are you from?", "出身はどこ？"],
      ["I heard from him yesterday.", "昨日彼から連絡があった。"],
    ],
    chunks: ["from now on", "from time to time", "hear from"],
  },
  {
    id: "with",
    rank: 49,
    type: "word",
    term: "with",
    ipa: "/wɪð, wɪθ/",
    pos: "preposition",
    meanings: ["〜と一緒に", "〜を持って", "〜で"],
    core: "何かがそばに付いている状態。",
    usage: ["同伴、道具、付属、関係を表す。", "deal with は相手に向き合って処理する感じ。"],
    examples: [
      ["I'm with a friend.", "友だちと一緒にいる。"],
      ["Can you help me with this?", "これ手伝ってくれる？"],
    ],
    chunks: ["with me", "with you", "deal with", "go with"],
  },
  {
    id: "he",
    rank: 50,
    type: "word",
    term: "he",
    ipa: "/hiː, i/",
    pos: "pronoun",
    meanings: ["彼は"],
    core: "話題の男性を主語として立てる。",
    usage: ["男性や男性として示される人を受ける。", "弱く読むと h が落ちて /i/ のように聞こえることがある。"],
    examples: [
      ["He said he was sorry.", "彼は謝っていたよ。"],
      ["Do you know where he is?", "彼がどこにいるか知ってる？"],
    ],
    chunks: ["he is", "he was", "he said"],
  },
  {
    id: "she",
    rank: 51,
    type: "word",
    term: "she",
    ipa: "/ʃiː/",
    pos: "pronoun",
    meanings: ["彼女は"],
    core: "話題の女性を主語として立てる。",
    usage: ["女性や女性として示される人を受ける。", "she's は she is / she has の両方になり得る。"],
    examples: [
      ["She's on her way.", "彼女は向かっているところ。"],
      ["She told me to wait.", "彼女は待つように言った。"],
    ],
    chunks: ["she is", "she was", "she said"],
  },
  {
    id: "make",
    rank: 52,
    type: "word",
    term: "make",
    ipa: "/meɪk/",
    pos: "verb",
    meanings: ["作る", "〜させる", "間に合う"],
    core: "材料や状況に働きかけて、新しい状態を作る。",
    usage: ["作成、原因、決定、到達に使う。", "make sense は意味が形になる感じ。"],
    examples: [
      ["That makes sense.", "それは納得できる。"],
      ["Can you make it tonight?", "今夜来られる？"],
    ],
    chunks: ["make sure", "make sense", "make it", "make up"],
  },
  {
    id: "look",
    rank: 53,
    type: "word",
    term: "look",
    ipa: "/lʊk/",
    pos: "verb",
    meanings: ["見る", "〜に見える", "探す"],
    core: "目や注意を向ける。",
    usage: ["見る動作、外見の判断、注意喚起に使う。", "Look, ... は話を切り出す合図。"],
    examples: [
      ["You look tired.", "疲れて見えるよ。"],
      ["I'm looking for my keys.", "鍵を探している。"],
    ],
    chunks: ["look at", "look for", "look like", "look up"],
  },
  {
    id: "think",
    rank: 54,
    type: "word",
    term: "think",
    ipa: "/θɪŋk/",
    pos: "verb",
    meanings: ["思う", "考える"],
    core: "頭の中で考えを動かし、意見として置く。",
    usage: ["意見、予想、判断を柔らかく出す。", "I think は断定を少しやわらげる。"],
    examples: [
      ["I think it's a good idea.", "いい考えだと思う。"],
      ["What do you think?", "どう思う？"],
    ],
    chunks: ["I think", "think about", "think of", "I don't think"],
  },
  {
    id: "take",
    rank: 55,
    type: "word",
    term: "take",
    ipa: "/teɪk/",
    pos: "verb",
    meanings: ["取る", "連れて行く", "時間がかかる", "受け入れる"],
    core: "何かを自分の側に取って、次の場所や状態へ運ぶ。",
    usage: ["物を取る、移動、時間、薬、選択に広く使う。", "take care は世話として受け持つ感じ。"],
    examples: [
      ["Take your time.", "ゆっくりでいいよ。"],
      ["It takes about ten minutes.", "10分くらいかかる。"],
    ],
    chunks: ["take care", "take a look", "take it easy", "take off"],
  },
  {
    id: "want",
    rank: 56,
    type: "word",
    term: "want",
    ipa: "/wɑːnt/",
    pos: "verb",
    meanings: ["欲しい", "〜したい"],
    core: "足りないものや向かいたい行動へ心が伸びる。",
    usage: ["欲求、希望、依頼に使う。", "wanna /ˈwɑːnə/ は want to の会話形。"],
    examples: [
      ["I want to try again.", "もう一度やってみたい。"],
      ["Do you want me to call?", "私が電話しようか？"],
    ],
    chunks: ["want to", "wanna", "do you want", "want me to"],
  },
  {
    id: "see",
    rank: 57,
    type: "word",
    term: "see",
    ipa: "/siː/",
    pos: "verb",
    meanings: ["見る", "会う", "わかる"],
    core: "目や理解で、対象をはっきり捉える。",
    usage: ["視覚、面会、理解、確認に使う。", "I see は理解した合図。"],
    examples: [
      ["I see what you mean.", "言いたいことはわかる。"],
      ["See you tomorrow.", "また明日。"],
    ],
    chunks: ["I see", "see you", "let's see", "see if"],
  },
  {
    id: "come",
    rank: 58,
    type: "word",
    term: "come",
    ipa: "/kʌm/",
    pos: "verb",
    meanings: ["来る", "起こる", "思い浮かぶ"],
    core: "話し手や基準点のほうへ近づく。",
    usage: ["移動、順番、出来事の到来に使う。", "come on は促し・驚き・不満まで広い。"],
    examples: [
      ["Can you come here?", "こっちに来てくれる？"],
      ["Come on, let's go.", "ほら、行こう。"],
    ],
    chunks: ["come on", "come back", "come with", "come up"],
  },
  {
    id: "time",
    rank: 59,
    type: "word",
    term: "time",
    ipa: "/taɪm/",
    pos: "noun",
    meanings: ["時間", "回", "時期"],
    core: "出来事が置かれる流れや一点。",
    usage: ["時刻、期間、回数、機会に使う。", "at the same time は同時に、または一方で。"],
    examples: [
      ["What time is it?", "今何時？"],
      ["I don't have time right now.", "今は時間がない。"],
    ],
    chunks: ["on time", "this time", "next time", "all the time"],
  },
  {
    id: "really",
    rank: 60,
    type: "word",
    term: "really",
    ipa: "/ˈriːəli/",
    pos: "adverb",
    meanings: ["本当に", "とても", "まさか"],
    core: "現実味や強さをぐっと濃くする。",
    usage: ["強調、確認、驚きに使う。", "Not really はやわらかい否定。"],
    examples: [
      ["I really appreciate it.", "本当に感謝しています。"],
      ["Really? I didn't know.", "本当？知らなかった。"],
    ],
    chunks: ["really good", "not really", "really want", "really appreciate"],
  },
  {
    id: "well",
    rank: 61,
    type: "word",
    term: "well",
    ipa: "/wel/",
    pos: "adverb/interjection",
    meanings: ["うまく", "さて", "ええと"],
    core: "状態が整っている、または発話を整える。",
    usage: ["良い状態、健康、話し始めの間に使う。", "Well, ... は答えを少し整えてから出す合図。"],
    examples: [
      ["That went well.", "うまくいったね。"],
      ["Well, I think you're right.", "ええと、君が正しいと思う。"],
    ],
    chunks: ["as well", "well done", "get well", "well then"],
  },
  {
    id: "now",
    rank: 62,
    type: "word",
    term: "now",
    ipa: "/naʊ/",
    pos: "adverb",
    meanings: ["今", "さあ", "今では"],
    core: "時間の焦点を現在へ合わせる。",
    usage: ["現在、すぐ、話題転換に使う。", "right now は今この瞬間を強める。"],
    examples: [
      ["I'm busy right now.", "今ちょっと忙しい。"],
      ["Now I understand.", "今わかった。"],
    ],
    chunks: ["right now", "now that", "from now on"],
  },
  {
    id: "then",
    rank: 63,
    type: "word",
    term: "then",
    ipa: "/ðen/",
    pos: "adverb",
    meanings: ["その時", "それから", "では"],
    core: "前の時点や条件の次に進める。",
    usage: ["順序、結果、条件からの結論に使う。", "See you then は約束した時を受ける。"],
    examples: [
      ["I'll see you then.", "その時に会おう。"],
      ["If you're ready, then let's start.", "準備ができたなら始めよう。"],
    ],
    chunks: ["and then", "back then", "by then", "then again"],
  },
  {
    id: "more",
    rank: 64,
    type: "word",
    term: "more",
    ipa: "/mɔːr/",
    pos: "determiner/adverb",
    meanings: ["もっと", "さらに", "より多く"],
    core: "今ある量や程度をもう一段増やす。",
    usage: ["量、程度、比較に使う。", "one more は会話でとても使いやすい。"],
    examples: [
      ["Can I have one more?", "もう一つもらえる？"],
      ["Tell me more about it.", "それについてもっと教えて。"],
    ],
    chunks: ["one more", "more than", "no more", "more like"],
  },
  {
    id: "no",
    rank: 65,
    type: "word",
    term: "no",
    ipa: "/noʊ/",
    pos: "determiner/interjection",
    meanings: ["いいえ", "まったくない", "禁止"],
    core: "選択肢や存在をはっきり閉じる。",
    usage: ["返答、数量ゼロ、否定の強調に使う。", "No worries は軽い返答として自然。"],
    examples: [
      ["No, that's okay.", "いや、大丈夫。"],
      ["I have no idea.", "まったくわからない。"],
    ],
    chunks: ["no problem", "no worries", "no idea", "no way"],
  },
  {
    id: "up",
    rank: 66,
    type: "word",
    term: "up",
    ipa: "/ʌp/",
    pos: "adverb",
    meanings: ["上へ", "完全に", "起きて"],
    core: "上方向、または状態を立ち上げて完了へ向ける。",
    usage: ["方向、増加、完了、準備に使う。", "What's up? は近況を聞く軽い挨拶。"],
    examples: [
      ["What's up?", "どうしたの？元気？"],
      ["I'll clean up later.", "あとで片づけるよ。"],
    ],
    chunks: ["pick up", "wake up", "show up", "clean up"],
  },
  {
    id: "people",
    rank: 67,
    type: "word",
    term: "people",
    ipa: "/ˈpiːpəl/",
    pos: "noun",
    meanings: ["人々", "みんな"],
    core: "個人をまとめて、人の集まりとして見る。",
    usage: ["一般の人々、特定グループ、民族に使う。", "many people より a lot of people が会話では自然なことが多い。"],
    examples: [
      ["A lot of people say that.", "多くの人がそう言う。"],
      ["People change.", "人は変わるものだ。"],
    ],
    chunks: ["a lot of people", "some people", "people like us"],
  },
  {
    id: "good",
    rank: 68,
    type: "word",
    term: "good",
    ipa: "/ɡʊd/",
    pos: "adjective",
    meanings: ["良い", "上手な", "十分な"],
    core: "目的や期待に合っていて、前向きに評価できる。",
    usage: ["品質、状態、能力、了承に使う。", "I'm good は断る時にも「大丈夫です」と使える。"],
    examples: [
      ["Sounds good.", "いいね。"],
      ["I'm good, thanks.", "大丈夫です、ありがとう。"],
    ],
    chunks: ["good at", "good for", "sounds good", "a good one"],
  },
  {
    id: "because",
    rank: 69,
    type: "word",
    term: "because",
    ipa: "/bɪˈkɔːz, bɪˈkʌz/",
    pos: "conjunction",
    meanings: ["なぜなら", "〜だから"],
    core: "出来事の後ろにある理由をつなげる。",
    usage: ["理由を明示する。", "because of の後ろには名詞を置く。"],
    examples: [
      ["I stayed home because I was sick.", "具合が悪かったので家にいた。"],
      ["Because of the rain, we canceled it.", "雨のせいで中止した。"],
    ],
    chunks: ["because of", "just because", "that's because"],
  },
  {
    id: "how",
    rank: 70,
    type: "word",
    term: "how",
    ipa: "/haʊ/",
    pos: "adverb",
    meanings: ["どう", "どのくらい", "なんて"],
    core: "方法・状態・程度の空欄をたずねる。",
    usage: ["方法、状態、程度、感嘆に使う。", "How about ...? は提案の定番。"],
    examples: [
      ["How are you doing?", "調子はどう？"],
      ["How did you know?", "どうしてわかったの？"],
    ],
    chunks: ["how about", "how much", "how long", "how come"],
  },
  {
    id: "kind-of",
    rank: 71,
    type: "phrase",
    term: "kind of",
    ipa: "/ˈkaɪnd əv, ˈkaɪnə/",
    pos: "phrase",
    meanings: ["ちょっと", "ある種の", "なんとなく"],
    core: "はっきり断定せず、近い種類や程度にぼかす。",
    usage: ["形容詞や感想を弱める。", "会話では kinda /ˈkaɪndə/ と短くなる。"],
    examples: [
      ["I'm kind of nervous.", "ちょっと緊張してる。"],
      ["It's kind of hard to explain.", "説明するのがちょっと難しい。"],
    ],
    chunks: ["kinda", "kind of like", "kind of hard"],
  },
  {
    id: "a-lot-of",
    rank: 72,
    type: "phrase",
    term: "a lot of",
    ipa: "/ə ˈlɑːt əv/",
    pos: "phrase",
    meanings: ["たくさんの", "多くの"],
    core: "量や数がまとまって多いことを、自然な会話の形で出す。",
    usage: ["数えられる名詞にも数えられない名詞にも使える。", "会話では many / much より柔らかいことが多い。"],
    examples: [
      ["I have a lot of work today.", "今日は仕事がたくさんある。"],
      ["A lot of people liked it.", "多くの人がそれを気に入った。"],
    ],
    chunks: ["a lot of time", "a lot of people", "thanks a lot"],
  },
  {
    id: "you-know",
    rank: 73,
    type: "phrase",
    term: "you know",
    ipa: "/jə ˈnoʊ/",
    pos: "phrase",
    meanings: ["ほら", "わかるでしょ", "えっと"],
    core: "相手と共有している感覚に軽く橋をかける。",
    usage: ["確認、間つなぎ、共感づくりに使う。", "使いすぎると口癖っぽく聞こえる。"],
    examples: [
      ["It was, you know, a little awkward.", "それは、ほら、ちょっと気まずかった。"],
      ["You know what I mean?", "言いたいことわかる？"],
    ],
    chunks: ["you know what", "you know what I mean"],
  },
  {
    id: "i-mean",
    rank: 74,
    type: "phrase",
    term: "I mean",
    ipa: "/aɪ ˈmiːn/",
    pos: "phrase",
    meanings: ["つまり", "いや", "というか"],
    core: "自分の言葉を言い直して、狙った意味に寄せる。",
    usage: ["訂正、補足、言い換え、ためらいに使う。", "強く言うと「本気で言っている」の意味にもなる。"],
    examples: [
      ["I mean, it's not impossible.", "つまり、不可能ではないよ。"],
      ["I didn't mean it that way.", "そういう意味で言ったんじゃない。"],
    ],
    chunks: ["what I mean", "I mean it", "you mean"],
  },
  {
    id: "have-to",
    rank: 75,
    type: "phrase",
    term: "have to",
    ipa: "/ˈhæv tə, ˈhæf tə/",
    pos: "phrase",
    meanings: ["〜しなければならない"],
    core: "外側の事情として、必要性を自分が抱えている。",
    usage: ["義務、必要、避けられない予定に使う。", "has to は /ˈhæz tə/ または /ˈhæs tə/。"],
    examples: [
      ["I have to get up early.", "早起きしなきゃ。"],
      ["You don't have to decide now.", "今決めなくてもいいよ。"],
    ],
    chunks: ["don't have to", "have to go", "have to be"],
  },
  {
    id: "want-to",
    rank: 76,
    type: "phrase",
    term: "want to",
    ipa: "/ˈwɑːnt tə, ˈwɑːnə/",
    pos: "phrase",
    meanings: ["〜したい"],
    core: "心がある行動へ向かっている。",
    usage: ["希望や誘いに使う。", "wanna はカジュアルな会話形。"],
    examples: [
      ["I want to learn this properly.", "これをちゃんと学びたい。"],
      ["Do you want to join us?", "一緒に来る？"],
    ],
    chunks: ["wanna", "want to be", "want to know"],
  },
  {
    id: "let-me",
    rank: 77,
    type: "phrase",
    term: "let me",
    ipa: "/ˈlet mi/",
    pos: "phrase",
    meanings: ["私に〜させて", "〜するね"],
    core: "自分が動く余地を相手に開けてもらう。",
    usage: ["申し出、確認、提案の前に置く。", "Let me know は知らせて、Let me see は考えさせて。"],
    examples: [
      ["Let me know when you're free.", "空いている時を教えて。"],
      ["Let me think about it.", "それについて考えさせて。"],
    ],
    chunks: ["let me know", "let me see", "let me check"],
  },
  {
    id: "go-ahead",
    rank: 78,
    type: "phrase",
    term: "go ahead",
    ipa: "/ˌɡoʊ əˈhed/",
    pos: "phrase",
    meanings: ["どうぞ", "先に進む", "始める"],
    core: "前に進む許可を出す。",
    usage: ["相手に許可する、先に行く、実行する時に使う。", "Please go ahead. は丁寧な「どうぞ」。"],
    examples: [
      ["Can I ask a question? Go ahead.", "質問していい？どうぞ。"],
      ["Go ahead and start without me.", "私なしで先に始めて。"],
    ],
    chunks: ["go right ahead", "go ahead and"],
  },
  {
    id: "make-sure",
    rank: 79,
    type: "phrase",
    term: "make sure",
    ipa: "/ˌmeɪk ˈʃʊr/",
    pos: "phrase",
    meanings: ["必ず確認する", "確実にする"],
    core: "曖昧な状態を、間違いない形に作る。",
    usage: ["確認、念押し、準備に使う。", "Make sure to ... は「必ず〜して」。"],
    examples: [
      ["Make sure you lock the door.", "必ずドアに鍵をかけて。"],
      ["I just want to make sure.", "念のため確認したいだけ。"],
    ],
    chunks: ["make sure to", "just to make sure"],
  },
  {
    id: "by-the-way",
    rank: 80,
    type: "phrase",
    term: "by the way",
    ipa: "/ˌbaɪ ðə ˈweɪ/",
    pos: "phrase",
    meanings: ["ところで", "ちなみに"],
    core: "本筋の道の横から、別の話題を差し込む。",
    usage: ["話題転換や補足を自然に始める。", "BTW はチャットでよく使う略。"],
    examples: [
      ["By the way, are you free tomorrow?", "ところで、明日空いてる？"],
      ["By the way, I liked your presentation.", "ちなみに、君の発表よかったよ。"],
    ],
    chunks: ["oh, by the way", "btw"],
  },
  {
    id: "maybe",
    rank: 81,
    type: "word",
    term: "maybe",
    ipa: "/ˈmeɪbi/",
    pos: "adverb",
    meanings: ["たぶん", "もしかすると"],
    core: "確定ではないけれど、可能性の方向に少し置く。",
    usage: ["断定を避ける時や、やわらかく提案する時によく使う。"],
    examples: [
      ["Maybe we should leave now.", "たぶん今出たほうがいいね。"],
      ["Maybe she's busy today.", "彼女は今日忙しいのかもしれない。"],
    ],
    chunks: ["maybe later", "maybe not", "maybe we should"],
  },
  {
    id: "should",
    rank: 82,
    type: "word",
    term: "should",
    ipa: "/ʃʊd/",
    pos: "modal verb",
    meanings: ["すべき", "したほうがいい", "たぶん"],
    core: "自然な方向・正しい方向へ軽く押す。",
    usage: ["助言、期待、軽い義務に使う。must よりやわらかい。"],
    examples: [
      ["You should get some rest.", "少し休んだほうがいいよ。"],
      ["It should be fine.", "たぶん大丈夫なはず。"],
    ],
    chunks: ["should be", "should have", "should we"],
  },
  {
    id: "could",
    rank: 83,
    type: "word",
    term: "could",
    ipa: "/kʊd/",
    pos: "modal verb",
    meanings: ["できた", "できるかもしれない", "してくれますか"],
    core: "可能性を少し開いたまま、控えめに差し出す。",
    usage: ["能力の過去、可能性、丁寧な依頼に使う。"],
    examples: [
      ["Could you say that again?", "もう一度言ってくれますか。"],
      ["We could try another way.", "別の方法を試せるかもしれない。"],
    ],
    chunks: ["could you", "could be", "could have"],
  },
  {
    id: "need",
    rank: 84,
    type: "word",
    term: "need",
    ipa: "/niːd/",
    pos: "verb / noun",
    meanings: ["必要とする", "必要"],
    core: "足りないものを満たす必要がある。",
    usage: ["必要な物・行動・条件を言う時の中心語。"],
    examples: [
      ["I need a little more time.", "もう少し時間が必要です。"],
      ["Do you need any help?", "何か手伝いが必要ですか。"],
    ],
    chunks: ["need to", "need help", "all I need"],
  },
  {
    id: "tell",
    rank: 85,
    type: "word",
    term: "tell",
    ipa: "/tel/",
    pos: "verb",
    meanings: ["伝える", "言う", "見分ける"],
    core: "相手に情報を渡して、わかる状態にする。",
    usage: ["tell 人 that / tell 人 to の形が会話で多い。"],
    examples: [
      ["Tell me what happened.", "何が起きたか教えて。"],
      ["I can't tell the difference.", "違いがわからない。"],
    ],
    chunks: ["tell me", "tell you what", "can't tell"],
  },
  {
    id: "ask",
    rank: 86,
    type: "word",
    term: "ask",
    ipa: "/æsk/",
    pos: "verb",
    meanings: ["尋ねる", "頼む"],
    core: "相手に答えや行動を求めて開く。",
    usage: ["質問にも依頼にも使う。ask for は物や助けを求める。"],
    examples: [
      ["Can I ask you something?", "ちょっと聞いてもいい？"],
      ["She asked for more time.", "彼女はもっと時間を求めた。"],
    ],
    chunks: ["ask about", "ask for", "ask someone to"],
  },
  {
    id: "give",
    rank: 87,
    type: "word",
    term: "give",
    ipa: "/ɡɪv/",
    pos: "verb",
    meanings: ["与える", "渡す"],
    core: "自分側から相手側へ何かを移す。",
    usage: ["物だけでなく、情報・機会・印象にも使う。"],
    examples: [
      ["Give me a second.", "少し待って。"],
      ["This gives us a chance.", "これでチャンスが生まれる。"],
    ],
    chunks: ["give me", "give up", "give someone a call"],
  },
  {
    id: "use",
    rank: 88,
    type: "word",
    term: "use",
    ipa: "/juːz/",
    pos: "verb",
    meanings: ["使う", "利用する"],
    core: "目的のために道具や方法を働かせる。",
    usage: ["道具、時間、表現、方法など幅広く使える。"],
    examples: [
      ["Can I use your phone?", "あなたの電話を使ってもいい？"],
      ["Use this phrase when you agree.", "賛成する時はこの表現を使って。"],
    ],
    chunks: ["use to", "make use of", "used to"],
  },
  {
    id: "work",
    rank: 89,
    type: "word",
    term: "work",
    ipa: "/wɝːk/",
    pos: "verb / noun",
    meanings: ["働く", "うまくいく", "仕事"],
    core: "力や仕組みが動いて、結果を出す。",
    usage: ["仕事だけでなく、方法や予定が合う時にも使う。"],
    examples: [
      ["Does this time work for you?", "この時間で都合はいい？"],
      ["The plan didn't work.", "その計画はうまくいかなかった。"],
    ],
    chunks: ["work for", "work on", "at work"],
  },
  {
    id: "feel",
    rank: 90,
    type: "word",
    term: "feel",
    ipa: "/fiːl/",
    pos: "verb",
    meanings: ["感じる", "思う", "触って感じる"],
    core: "体や心に内側から感覚が立ち上がる。",
    usage: ["感情、体調、印象を言う時の基本語。"],
    examples: [
      ["I feel better now.", "今は気分がよくなった。"],
      ["It feels a little strange.", "少し変な感じがする。"],
    ],
    chunks: ["feel like", "feel better", "how do you feel"],
  },
  {
    id: "try",
    rank: 91,
    type: "word",
    term: "try",
    ipa: "/traɪ/",
    pos: "verb / noun",
    meanings: ["試す", "やってみる", "努力する"],
    core: "結果が未確定でも、まず手を伸ばす。",
    usage: ["try to は努力、try -ing は試しにやる感覚。"],
    examples: [
      ["Let's try again tomorrow.", "明日もう一度やってみよう。"],
      ["I'm trying to understand.", "理解しようとしているところです。"],
    ],
    chunks: ["try to", "try again", "give it a try"],
  },
  {
    id: "call",
    rank: 92,
    type: "word",
    term: "call",
    ipa: "/kɔːl/",
    pos: "verb / noun",
    meanings: ["電話する", "呼ぶ", "名づける"],
    core: "声や名前で相手へ届かせる。",
    usage: ["電話、呼び名、判断の宣言に使う。"],
    examples: [
      ["I'll call you later.", "あとで電話するね。"],
      ["What do you call this?", "これは何と呼びますか。"],
    ],
    chunks: ["call back", "call me", "phone call"],
  },
  {
    id: "talk",
    rank: 93,
    type: "word",
    term: "talk",
    ipa: "/tɔːk/",
    pos: "verb / noun",
    meanings: ["話す", "話し合う"],
    core: "言葉をやり取りして場を作る。",
    usage: ["speak より会話・相談の感じが強い。"],
    examples: [
      ["Can we talk for a minute?", "少し話せる？"],
      ["We talked about the problem.", "その問題について話した。"],
    ],
    chunks: ["talk about", "talk to", "small talk"],
  },
  {
    id: "wait",
    rank: 94,
    type: "word",
    term: "wait",
    ipa: "/weɪt/",
    pos: "verb",
    meanings: ["待つ"],
    core: "動かずに、次の時点が来るのを受ける。",
    usage: ["命令の Wait. は会話で『ちょっと待って』の意味。"],
    examples: [
      ["Wait, what did you say?", "待って、何て言った？"],
      ["I'll wait here.", "ここで待つよ。"],
    ],
    chunks: ["wait for", "can't wait", "wait a minute"],
  },
  {
    id: "help",
    rank: 95,
    type: "word",
    term: "help",
    ipa: "/help/",
    pos: "verb / noun",
    meanings: ["助ける", "助け"],
    core: "相手の負担を軽くして進めるようにする。",
    usage: ["依頼、申し出、問題解決で頻出。"],
    examples: [
      ["Can you help me with this?", "これを手伝ってくれる？"],
      ["That really helped.", "それは本当に助かった。"],
    ],
    chunks: ["help with", "help out", "can't help"],
  },
  {
    id: "put",
    rank: 96,
    type: "word",
    term: "put",
    ipa: "/pʊt/",
    pos: "verb",
    meanings: ["置く", "入れる", "表現する"],
    core: "何かをある場所・状態に移して置く。",
    usage: ["物理的な位置だけでなく、言葉や状態にも使う。"],
    examples: [
      ["Put it on the table.", "それをテーブルに置いて。"],
      ["How should I put this?", "これをどう言えばいいかな。"],
    ],
    chunks: ["put on", "put it", "put together"],
  },
  {
    id: "keep",
    rank: 97,
    type: "word",
    term: "keep",
    ipa: "/kiːp/",
    pos: "verb",
    meanings: ["保つ", "持ち続ける", "続ける"],
    core: "ある状態を離さず、そのまま持つ。",
    usage: ["keep -ing は行動を続ける意味。"],
    examples: [
      ["Keep going.", "そのまま続けて。"],
      ["I'll keep this in mind.", "それを覚えておくよ。"],
    ],
    chunks: ["keep going", "keep in mind", "keep it"],
  },
  {
    id: "find",
    rank: 98,
    type: "word",
    term: "find",
    ipa: "/faɪnd/",
    pos: "verb",
    meanings: ["見つける", "わかる", "感じる"],
    core: "探していたものや気づいていなかったものに出会う。",
    usage: ["物を見つけるだけでなく、結論や印象にも使う。"],
    examples: [
      ["I can't find my keys.", "鍵が見つからない。"],
      ["I found it really useful.", "それは本当に役に立つと思った。"],
    ],
    chunks: ["find out", "find it", "can't find"],
  },
  {
    id: "mean",
    rank: 99,
    type: "word",
    term: "mean",
    ipa: "/miːn/",
    pos: "verb / adjective",
    meanings: ["意味する", "本気で言う", "意地悪な"],
    core: "言葉や行動の内側にある意図を指す。",
    usage: ["What do you mean? は会話の必須表現。"],
    examples: [
      ["What do you mean?", "どういう意味？"],
      ["I didn't mean to hurt you.", "傷つけるつもりはなかった。"],
    ],
    chunks: ["what do you mean", "mean to", "I mean"],
  },
  {
    id: "leave",
    rank: 100,
    type: "word",
    term: "leave",
    ipa: "/liːv/",
    pos: "verb",
    meanings: ["去る", "残す", "置いていく"],
    core: "ある場所や状態から離れて、何かを後ろに残す。",
    usage: ["出発、放置、メッセージを残す時に使う。"],
    examples: [
      ["I have to leave soon.", "もうすぐ行かなきゃ。"],
      ["Leave it there.", "それはそこに置いておいて。"],
    ],
    chunks: ["leave soon", "leave it", "leave a message"],
  },
  {
    id: "right",
    rank: 101,
    type: "word",
    term: "right",
    ipa: "/raɪt/",
    pos: "adjective / adverb / noun",
    meanings: ["正しい", "右", "ちょうど"],
    core: "ずれがなく、ぴったり合っている。",
    usage: ["同意の Right.、確認の right?、強調の right now で頻出。"],
    examples: [
      ["You're right.", "あなたの言う通り。"],
      ["I'll do it right now.", "今すぐやります。"],
    ],
    chunks: ["right now", "right away", "all right"],
  },
  {
    id: "wrong",
    rank: 102,
    type: "word",
    term: "wrong",
    ipa: "/rɔːŋ/",
    pos: "adjective",
    meanings: ["間違った", "具合が悪い"],
    core: "本来の位置や正しさから外れている。",
    usage: ["答え、判断、状況、体調に使う。"],
    examples: [
      ["I was wrong about that.", "それについては私が間違っていた。"],
      ["What's wrong?", "どうしたの？"],
    ],
    chunks: ["go wrong", "what's wrong", "wrong with"],
  },
  {
    id: "sure",
    rank: 103,
    type: "word",
    term: "sure",
    ipa: "/ʃʊr/",
    pos: "adjective / adverb",
    meanings: ["確かな", "もちろん"],
    core: "揺れずに確信がある。",
    usage: ["Sure. は返事として『もちろん』『いいよ』。"],
    examples: [
      ["Are you sure?", "本当に確か？"],
      ["Sure, no problem.", "もちろん、問題ないよ。"],
    ],
    chunks: ["make sure", "for sure", "sure thing"],
  },
  {
    id: "sorry",
    rank: 104,
    type: "word",
    term: "sorry",
    ipa: "/ˈsɑːri/",
    pos: "adjective",
    meanings: ["ごめんなさい", "残念に思って"],
    core: "相手に負担や残念さをかけたことへ心を向ける。",
    usage: ["謝罪だけでなく、聞き返しの Sorry? にも使う。"],
    examples: [
      ["Sorry, I didn't hear you.", "ごめん、聞こえなかった。"],
      ["I'm sorry about that.", "それについては申し訳ないです。"],
    ],
    chunks: ["I'm sorry", "sorry about", "sorry for"],
  },
  {
    id: "thank",
    rank: 105,
    type: "word",
    term: "thank",
    ipa: "/θæŋk/",
    pos: "verb",
    meanings: ["感謝する"],
    core: "相手の行為を受け取り、ありがたさを返す。",
    usage: ["Thank you. が基本。Thanks は少しカジュアル。"],
    examples: [
      ["Thank you for coming.", "来てくれてありがとう。"],
      ["I want to thank everyone here.", "ここにいる皆さんに感謝したいです。"],
    ],
    chunks: ["thank you", "thank you for", "thanks a lot"],
  },
  {
    id: "please",
    rank: 106,
    type: "word",
    term: "please",
    ipa: "/pliːz/",
    pos: "adverb / verb",
    meanings: ["お願いします", "喜ばせる"],
    core: "相手に配慮しながら、してほしい方向へ添える。",
    usage: ["依頼を丁寧にする。位置で響きが少し変わる。"],
    examples: [
      ["Please wait here.", "ここでお待ちください。"],
      ["Could you help me, please?", "手伝っていただけますか。"],
    ],
    chunks: ["please wait", "yes please", "please let me know"],
  },
  {
    id: "i-dont-know",
    rank: 107,
    type: "phrase",
    term: "I don't know",
    ipa: "/aɪ doʊnt noʊ/",
    pos: "phrase",
    meanings: ["わからない", "知らない"],
    core: "自分の中に答えがないことをそのまま出す。",
    usage: ["本当に知らない時も、迷っている時の時間稼ぎにも使う。"],
    examples: [
      ["I don't know the answer.", "答えがわからない。"],
      ["I don't know, maybe later.", "どうだろう、たぶん後で。"],
    ],
    chunks: ["I don't know why", "I don't know if", "I don't know yet"],
  },
  {
    id: "i-think",
    rank: 108,
    type: "phrase",
    term: "I think",
    ipa: "/aɪ θɪŋk/",
    pos: "phrase",
    meanings: ["私は思う", "たぶん"],
    core: "自分の頭の中の判断として、少し控えめに置く。",
    usage: ["意見をやわらかく言う時の最頻出フレーズ。"],
    examples: [
      ["I think you're right.", "あなたが正しいと思う。"],
      ["I think we should go.", "行ったほうがいいと思う。"],
    ],
    chunks: ["I think so", "I don't think", "I think we should"],
  },
  {
    id: "you-know-what",
    rank: 109,
    type: "phrase",
    term: "you know what",
    ipa: "/ju noʊ wʌt/",
    pos: "phrase",
    meanings: ["あのさ", "そうだ", "わかる？"],
    core: "相手の注意をこちらの考えに向け直す。",
    usage: ["話題転換、思いつき、強調の前置きに使う。"],
    examples: [
      ["You know what, let's take a break.", "そうだ、休憩しよう。"],
      ["You know what I mean?", "言いたいことわかる？"],
    ],
    chunks: ["you know what I mean", "you know what to do"],
  },
  {
    id: "come-on",
    rank: 110,
    type: "phrase",
    term: "come on",
    ipa: "/kʌm ɑːn/",
    pos: "phrase",
    meanings: ["お願い", "まさか", "早く", "しっかりして"],
    core: "相手や状況をこちらへ動かそうと押す。",
    usage: ["励まし、催促、不満、驚きで広く使う。"],
    examples: [
      ["Come on, you can do it.", "ほら、君ならできるよ。"],
      ["Oh, come on. That's not fair.", "おいおい、それは公平じゃないよ。"],
    ],
    chunks: ["come on in", "come on over", "oh come on"],
  },
  {
    id: "look-at",
    rank: 111,
    type: "phrase",
    term: "look at",
    ipa: "/lʊk æt/",
    pos: "phrase",
    meanings: ["見る", "注目する", "考える"],
    core: "視線や意識を一点に向ける。",
    usage: ["実際に見る時も、問題を検討する時も使う。"],
    examples: [
      ["Look at this picture.", "この写真を見て。"],
      ["Let's look at the numbers.", "数字を見てみよう。"],
    ],
    chunks: ["look at me", "look at this", "take a look at"],
  },
  {
    id: "talk-about",
    rank: 112,
    type: "phrase",
    term: "talk about",
    ipa: "/tɔːk əˈbaʊt/",
    pos: "phrase",
    meanings: ["について話す"],
    core: "話の場をある話題の周りに置く。",
    usage: ["会話・会議・相談のテーマを示す基本形。"],
    examples: [
      ["Can we talk about this later?", "これについて後で話せる？"],
      ["They talked about their plans.", "彼らは計画について話した。"],
    ],
    chunks: ["talk about it", "nothing to talk about", "talk about why"],
  },
  {
    id: "find-out",
    rank: 113,
    type: "phrase",
    term: "find out",
    ipa: "/faɪnd aʊt/",
    pos: "phrasal verb",
    meanings: ["突き止める", "知る"],
    core: "隠れていた情報を外へ見つけ出す。",
    usage: ["調べてわかる、後で知る、の両方に使う。"],
    examples: [
      ["I'll find out what happened.", "何が起きたか調べてみる。"],
      ["How did you find out?", "どうやって知ったの？"],
    ],
    chunks: ["find out about", "find out why", "find out if"],
  },
  {
    id: "check-out",
    rank: 114,
    type: "phrase",
    term: "check out",
    ipa: "/tʃek aʊt/",
    pos: "phrasal verb",
    meanings: ["確認する", "見てみる", "支払いを済ませる"],
    core: "外へ目を向けて、確かめる。",
    usage: ["おすすめを見る、店やホテルで会計する時にも使う。"],
    examples: [
      ["Check out this app.", "このアプリ見てみて。"],
      ["We need to check out by ten.", "10時までにチェックアウトしないといけない。"],
    ],
    chunks: ["check this out", "check it out", "check out of"],
  },
  {
    id: "pick-up",
    rank: 115,
    type: "phrase",
    term: "pick up",
    ipa: "/pɪk ʌp/",
    pos: "phrasal verb",
    meanings: ["拾う", "迎えに行く", "身につける"],
    core: "下や外にあるものを自分側へ取り上げる。",
    usage: ["物、人、知識、電話など幅広く取る感覚。"],
    examples: [
      ["Can you pick up the package?", "その荷物を取ってきてくれる？"],
      ["I picked up a few new words.", "新しい単語をいくつか身につけた。"],
    ],
    chunks: ["pick me up", "pick it up", "pick up on"],
  },
  {
    id: "right-now",
    rank: 116,
    type: "phrase",
    term: "right now",
    ipa: "/raɪt naʊ/",
    pos: "phrase",
    meanings: ["今すぐ", "今この瞬間"],
    core: "時間の針を今ここにぴったり合わせる。",
    usage: ["緊急性や現在の状態を強める。"],
    examples: [
      ["I need it right now.", "今すぐそれが必要です。"],
      ["I'm busy right now.", "今ちょっと忙しい。"],
    ],
    chunks: ["not right now", "right now I'm", "do it right now"],
  },
  {
    id: "a-little",
    rank: 117,
    type: "phrase",
    term: "a little",
    ipa: "/ə ˈlɪtl/",
    pos: "phrase",
    meanings: ["少し", "ちょっと"],
    core: "小さい量だけ加える。",
    usage: ["量、程度、感情をやわらかく言う。"],
    examples: [
      ["I'm a little tired.", "少し疲れている。"],
      ["Can you speak a little slower?", "少しゆっくり話してくれる？"],
    ],
    chunks: ["a little bit", "a little more", "a little later"],
  },
  {
    id: "a-couple-of",
    rank: 118,
    type: "phrase",
    term: "a couple of",
    ipa: "/ə ˈkʌpl əv/",
    pos: "phrase",
    meanings: ["2、3の", "いくつかの"],
    core: "少数のまとまりをざっくり示す。",
    usage: ["厳密に2つとは限らず、少しだけの意味でよく使う。"],
    examples: [
      ["I have a couple of questions.", "いくつか質問があります。"],
      ["Give me a couple of minutes.", "2、3分ください。"],
    ],
    chunks: ["a couple of days", "a couple of times", "a couple of things"],
  },
  {
    id: "sort-of",
    rank: 119,
    type: "phrase",
    term: "sort of",
    ipa: "/ˈsɔːrt əv/",
    pos: "phrase",
    meanings: ["ちょっと", "ある意味", "まあ"],
    core: "はっきり断定せず、近い種類としてぼかす。",
    usage: ["断定をやわらげる会話表現。kind of も近い。"],
    examples: [
      ["I'm sort of nervous.", "ちょっと緊張している。"],
      ["It's sort of hard to explain.", "説明するのが少し難しい。"],
    ],
    chunks: ["sort of like", "sort of thing", "kind of"],
  },
  {
    id: "as-well",
    rank: 120,
    type: "phrase",
    term: "as well",
    ipa: "/æz wel/",
    pos: "phrase",
    meanings: ["もまた", "そのうえ"],
    core: "すでにあるものに、同じ方向で追加する。",
    usage: ["too と似るが、少し丁寧・文末でよく使う。"],
    examples: [
      ["Can I come as well?", "私も行っていい？"],
      ["She speaks English as well.", "彼女も英語を話す。"],
    ],
    chunks: ["as well as", "might as well", "you as well"],
  },
  {
    id: "never",
    rank: 121,
    type: "word",
    term: "never",
    ipa: "/ˈnevər/",
    pos: "adverb",
    meanings: ["一度もない", "決してない"],
    core: "時間のどこにも起きないと切る。",
    usage: ["経験の否定、強い否定、驚きの返答に使う。"],
    examples: [
      ["I've never been there.", "そこへ行ったことがない。"],
      ["Never mind.", "気にしないで。"],
    ],
    chunks: ["never mind", "never again", "never seen"],
  },
  {
    id: "always",
    rank: 122,
    type: "word",
    term: "always",
    ipa: "/ˈɔːlweɪz/",
    pos: "adverb",
    meanings: ["いつも", "常に"],
    core: "時間の流れの中で毎回そこにある。",
    usage: ["習慣、性格、変わらない事実に使う。"],
    examples: [
      ["You're always welcome here.", "ここにはいつでも来ていいよ。"],
      ["I always forget his name.", "彼の名前をいつも忘れてしまう。"],
    ],
    chunks: ["almost always", "as always", "always have"],
  },
  {
    id: "still",
    rank: 123,
    type: "word",
    term: "still",
    ipa: "/stɪl/",
    pos: "adverb / adjective",
    meanings: ["まだ", "それでも", "静かな"],
    core: "時間が進んでも状態が残っている。",
    usage: ["継続、意外な残存、比較の強調に使う。"],
    examples: [
      ["Are you still there?", "まだそこにいる？"],
      ["I still don't understand.", "まだ理解できていない。"],
    ],
    chunks: ["still here", "still have", "still need"],
  },
  {
    id: "even",
    rank: 124,
    type: "word",
    term: "even",
    ipa: "/ˈiːvən/",
    pos: "adverb / adjective",
    meanings: ["でさえ", "さらに", "平らな"],
    core: "普通の範囲を越えた点まで含める。",
    usage: ["驚きや強調を入れる時によく使う。"],
    examples: [
      ["Even I can do that.", "私でさえそれはできる。"],
      ["It's even better now.", "今はさらに良くなっている。"],
    ],
    chunks: ["even if", "even though", "not even"],
  },
  {
    id: "actually",
    rank: 125,
    type: "word",
    term: "actually",
    ipa: "/ˈæktʃuəli/",
    pos: "adverb",
    meanings: ["実は", "実際に"],
    core: "思い込みではなく、現実側へ戻す。",
    usage: ["訂正、意外な事実、やわらかい反対に使う。"],
    examples: [
      ["Actually, I have a question.", "実は質問があります。"],
      ["It's actually pretty easy.", "実際かなり簡単です。"],
    ],
    chunks: ["actually no", "actually think", "not actually"],
  },
  {
    id: "probably",
    rank: 126,
    type: "word",
    term: "probably",
    ipa: "/ˈprɑːbəbli/",
    pos: "adverb",
    meanings: ["おそらく", "たぶん"],
    core: "可能性が高いほうへ判断を置く。",
    usage: ["maybe より確信が強い。"],
    examples: [
      ["I'll probably be late.", "たぶん遅れます。"],
      ["That's probably true.", "それはおそらく本当です。"],
    ],
    chunks: ["probably not", "probably be", "probably should"],
  },
  {
    id: "already",
    rank: 127,
    type: "word",
    term: "already",
    ipa: "/ɔːlˈredi/",
    pos: "adverb",
    meanings: ["すでに", "もう"],
    core: "予想より前に、完了した状態にある。",
    usage: ["完了、驚き、少し急かす感じにも使う。"],
    examples: [
      ["I already told you.", "もう言ったよ。"],
      ["Are you done already?", "もう終わったの？"],
    ],
    chunks: ["already have", "already done", "already know"],
  },
  {
    id: "before",
    rank: 128,
    type: "word",
    term: "before",
    ipa: "/bɪˈfɔːr/",
    pos: "preposition / conjunction / adverb",
    meanings: ["前に", "以前に"],
    core: "時間や位置で、基準より手前にある。",
    usage: ["時間の前後、経験の有無、順序に使う。"],
    examples: [
      ["I've heard that before.", "それは前に聞いたことがある。"],
      ["Call me before you leave.", "出る前に電話して。"],
    ],
    chunks: ["before that", "before you go", "never before"],
  },
  {
    id: "after",
    rank: 129,
    type: "word",
    term: "after",
    ipa: "/ˈæftər/",
    pos: "preposition / conjunction / adverb",
    meanings: ["後に", "追って"],
    core: "基準のあとに続く。",
    usage: ["時間の順序、追跡、名前の由来に使う。"],
    examples: [
      ["Let's talk after lunch.", "昼食後に話そう。"],
      ["What happened after that?", "その後何が起きたの？"],
    ],
    chunks: ["after that", "after all", "right after"],
  },
  {
    id: "here",
    rank: 130,
    type: "word",
    term: "here",
    ipa: "/hɪr/",
    pos: "adverb",
    meanings: ["ここに", "こちらへ"],
    core: "話し手がいる場所や注目点に引き寄せる。",
    usage: ["場所、提示、到着の表現で使う。"],
    examples: [
      ["Come here for a second.", "ちょっとこっちに来て。"],
      ["Here is my number.", "これが私の番号です。"],
    ],
    chunks: ["right here", "over here", "here you go"],
  },
  {
    id: "where",
    rank: 131,
    type: "word",
    term: "where",
    ipa: "/wer/",
    pos: "adverb / conjunction",
    meanings: ["どこ", "場所"],
    core: "場所の空白をたずねる。",
    usage: ["場所を聞く疑問詞。関係詞としてもよく使う。"],
    examples: [
      ["Where are you now?", "今どこにいる？"],
      ["This is where I live.", "ここが私の住んでいる場所です。"],
    ],
    chunks: ["where is", "where are", "where to"],
  },
  {
    id: "when",
    rank: 132,
    type: "word",
    term: "when",
    ipa: "/wen/",
    pos: "adverb / conjunction",
    meanings: ["いつ", "するとき"],
    core: "時間の空白をたずねる。",
    usage: ["時刻、予定、条件に近い時間の接続で使う。"],
    examples: [
      ["When did you get here?", "いつここに着いたの？"],
      ["Call me when you're ready.", "準備ができたら電話して。"],
    ],
    chunks: ["when you", "when did", "since when"],
  },
  {
    id: "why",
    rank: 133,
    type: "word",
    term: "why",
    ipa: "/waɪ/",
    pos: "adverb",
    meanings: ["なぜ", "理由"],
    core: "原因や理由の空白をたずねる。",
    usage: ["理由を聞く時の基本。Why not? は提案にもなる。"],
    examples: [
      ["Why are you laughing?", "なぜ笑っているの？"],
      ["Why not try it?", "試してみたらどう？"],
    ],
    chunks: ["why not", "why don't we", "that's why"],
  },
  {
    id: "who",
    rank: 134,
    type: "word",
    term: "who",
    ipa: "/huː/",
    pos: "pronoun",
    meanings: ["誰", "する人"],
    core: "人の空白をたずねる。",
    usage: ["人物を聞く疑問詞。関係代名詞としても使う。"],
    examples: [
      ["Who told you that?", "誰がそれを言ったの？"],
      ["I know someone who can help.", "助けてくれる人を知っている。"],
    ],
    chunks: ["who is", "who knows", "who can"],
  },
  {
    id: "which",
    rank: 135,
    type: "word",
    term: "which",
    ipa: "/wɪtʃ/",
    pos: "pronoun / determiner",
    meanings: ["どちら", "どの"],
    core: "限られた選択肢の中から一つを指す。",
    usage: ["選択、確認、関係詞として使う。"],
    examples: [
      ["Which one do you like?", "どれが好き？"],
      ["I don't know which way to go.", "どちらへ行けばいいかわからない。"],
    ],
    chunks: ["which one", "which way", "which means"],
  },
  {
    id: "other",
    rank: 136,
    type: "word",
    term: "other",
    ipa: "/ˈʌðər/",
    pos: "adjective / pronoun",
    meanings: ["他の", "別の"],
    core: "今見ているものとは別側にある。",
    usage: ["もう一方、別の人・物・方法を示す。"],
    examples: [
      ["Do you have any other questions?", "他に質問はありますか。"],
      ["The other one is better.", "もう一つのほうが良い。"],
    ],
    chunks: ["each other", "the other day", "other than"],
  },
  {
    id: "another",
    rank: 137,
    type: "word",
    term: "another",
    ipa: "/əˈnʌðər/",
    pos: "determiner / pronoun",
    meanings: ["もう一つの", "別の"],
    core: "今あるものに加えて、別の一つを出す。",
    usage: ["追加の一つ、代わりの一つを言う。"],
    examples: [
      ["Can I have another one?", "もう一つもらえますか。"],
      ["Let's try another way.", "別の方法を試そう。"],
    ],
    chunks: ["another one", "another way", "another time"],
  },
  {
    id: "same",
    rank: 138,
    type: "word",
    term: "same",
    ipa: "/seɪm/",
    pos: "adjective / pronoun",
    meanings: ["同じ"],
    core: "二つのものがずれずに重なる。",
    usage: ["同意、比較、変化なしを言う時に使う。"],
    examples: [
      ["I feel the same way.", "私も同じように感じます。"],
      ["It's the same as before.", "前と同じです。"],
    ],
    chunks: ["same here", "the same as", "at the same time"],
  },
  {
    id: "different",
    rank: 139,
    type: "word",
    term: "different",
    ipa: "/ˈdɪfrənt/",
    pos: "adjective",
    meanings: ["違う", "別の"],
    core: "比べた時に同じ線上に重ならない。",
    usage: ["違い、別案、予想外の印象に使う。"],
    examples: [
      ["This is different from what I expected.", "これは予想していたものと違う。"],
      ["We need a different approach.", "別のやり方が必要です。"],
    ],
    chunks: ["different from", "different kind of", "look different"],
  },
  {
    id: "little",
    rank: 140,
    type: "word",
    term: "little",
    ipa: "/ˈlɪtl/",
    pos: "adjective / adverb",
    meanings: ["小さい", "少しの"],
    core: "量や大きさが小さい。",
    usage: ["a little で肯定的な『少し』、little だけだと不足感が出やすい。"],
    examples: [
      ["It's just a little problem.", "それはほんの小さな問題です。"],
      ["I have little time today.", "今日は時間がほとんどない。"],
    ],
    chunks: ["a little", "little bit", "little by little"],
  },
  {
    id: "big",
    rank: 141,
    type: "word",
    term: "big",
    ipa: "/bɪɡ/",
    pos: "adjective",
    meanings: ["大きい", "重要な"],
    core: "サイズや影響が大きく広がる。",
    usage: ["物理的な大きさだけでなく、出来事や感情にも使う。"],
    examples: [
      ["That's a big deal.", "それは大きなことだよ。"],
      ["We have a big meeting tomorrow.", "明日は大事な会議がある。"],
    ],
    chunks: ["big deal", "big enough", "big part"],
  },
  {
    id: "new",
    rank: 142,
    type: "word",
    term: "new",
    ipa: "/nuː/",
    pos: "adjective",
    meanings: ["新しい", "初めての"],
    core: "まだ使われていない、または経験に入ってきたばかり。",
    usage: ["物、情報、経験、人間関係に使う。"],
    examples: [
      ["I learned a new word today.", "今日は新しい単語を覚えた。"],
      ["This is new to me.", "これは私には初めてです。"],
    ],
    chunks: ["new to", "brand new", "new idea"],
  },
  {
    id: "old",
    rank: 143,
    type: "word",
    term: "old",
    ipa: "/oʊld/",
    pos: "adjective",
    meanings: ["古い", "年を取った", "昔からの"],
    core: "時間を長く通ってきた。",
    usage: ["年齢、古さ、なじみの関係に使う。"],
    examples: [
      ["How old are you?", "何歳ですか。"],
      ["I found an old photo.", "古い写真を見つけた。"],
    ],
    chunks: ["old friend", "years old", "old enough"],
  },
  {
    id: "first",
    rank: 144,
    type: "word",
    term: "first",
    ipa: "/fɝːst/",
    pos: "adjective / adverb / noun",
    meanings: ["最初の", "まず"],
    core: "順番のいちばん前にある。",
    usage: ["順序、優先順位、初体験に使う。"],
    examples: [
      ["Let me ask one thing first.", "まず一つ聞かせて。"],
      ["This is my first time here.", "ここは初めてです。"],
    ],
    chunks: ["first time", "at first", "first of all"],
  },
  {
    id: "last",
    rank: 145,
    type: "word",
    term: "last",
    ipa: "/læst/",
    pos: "adjective / verb / adverb",
    meanings: ["最後の", "前回の", "続く"],
    core: "列の終わり、または時間の終わりまで残る。",
    usage: ["最後、直近の過去、持続の意味がある。"],
    examples: [
      ["What did you do last night?", "昨夜何をしたの？"],
      ["This battery won't last long.", "この電池は長く持たない。"],
    ],
    chunks: ["last night", "last time", "at last"],
  },
  {
    id: "thing",
    rank: 146,
    type: "word",
    term: "thing",
    ipa: "/θɪŋ/",
    pos: "noun",
    meanings: ["もの", "こと"],
    core: "名前をまだ絞らない対象をひとまとまりで指す。",
    usage: ["物、出来事、話題、重要点を広く受ける。"],
    examples: [
      ["I have one thing to say.", "一つ言いたいことがある。"],
      ["What's that thing called?", "あれは何て呼ぶの？"],
    ],
    chunks: ["one thing", "the thing is", "kind of thing"],
  },
  {
    id: "way",
    rank: 147,
    type: "word",
    term: "way",
    ipa: "/weɪ/",
    pos: "noun / adverb",
    meanings: ["方法", "道", "かなり"],
    core: "目的へ進む道筋ややり方。",
    usage: ["方法、方向、距離、強調の way too で頻出。"],
    examples: [
      ["There has to be another way.", "別の方法があるはず。"],
      ["This is way too expensive.", "これはかなり高すぎる。"],
    ],
    chunks: ["by the way", "no way", "way too"],
  },
  {
    id: "place",
    rank: 148,
    type: "word",
    term: "place",
    ipa: "/pleɪs/",
    pos: "noun / verb",
    meanings: ["場所", "置く"],
    core: "ものや人が位置を持つ点。",
    usage: ["場所、店、居場所、順位にも使う。"],
    examples: [
      ["This place is nice.", "この場所いいね。"],
      ["Put it back in the right place.", "それを正しい場所に戻して。"],
    ],
    chunks: ["take place", "in place", "your place"],
  },
  {
    id: "day",
    rank: 149,
    type: "word",
    term: "day",
    ipa: "/deɪ/",
    pos: "noun",
    meanings: ["日", "一日"],
    core: "朝から夜までの一つの時間単位。",
    usage: ["予定、経験、あいさつ、期間に使う。"],
    examples: [
      ["Have a good day.", "よい一日を。"],
      ["I had a long day.", "長い一日だった。"],
    ],
    chunks: ["one day", "every day", "these days"],
  },
  {
    id: "money",
    rank: 150,
    type: "word",
    term: "money",
    ipa: "/ˈmʌni/",
    pos: "noun",
    meanings: ["お金"],
    core: "価値を交換するための共通の手段。",
    usage: ["支払い、費用、余裕、価値の話で使う。"],
    examples: [
      ["I don't have enough money.", "十分なお金がない。"],
      ["This saves money and time.", "これはお金と時間を節約できる。"],
    ],
    chunks: ["make money", "save money", "spend money"],
  },
];
